### ISSUE TITLE
Duplicate key error

### ISSUE THREAD

**Issue by athos-ribeiro** [fedora-infra/bodhi#1005]
Hello,

I recently changed my FAS account name and am currently migrating all my data, activities and packages to that account.

I am using my main gmail email for that. In order to do so, I changed my old account email to use a secondary email I own.

When I try to login in bodhi, I get the following error:

500 Server Error

(IntegrityError) duplicate key value violates unique constraint "users_email_key" DETAIL: Key (email)=(athoscribeiro@gmail.com) already exists. 'INSERT INTO users (name, email, show_popups) VALUES (%(name)s, %(email)s, %(show_popups)s) RETURNING users.id' {'show_popups': True, 'name': u'athoscr', 'email': u'athoscribeiro@gmail.com'}

**Comment by bowlofeggs** [comment]
Interesting - it seems that we could solve this programmatically two ways:
1. We could rely on the FAS account name for uniqueness and drop the uniqueness constraint on e-mail address.
2. We could be more diligent about checking up on FAS data and refreshing it from time to time, so that we would know when users do things like changing their e-mail address.

In fact, I've noticed that Bodhi still uses my old e-mail address, even though I updated to the new one in FAS a while ago, so solving that second problem would be a good idea anyway.

In your specific case, we can probably get an admin from #fedora-admin to log into the database and manually fix your old account's e-mail address to match what it was set to in FAS. Once that is done, I expect that a new login from your new account would allow that INSERT statement to succeed.

**Comment by athos-ribeiro** [comment]
> ```
> We could rely on the FAS account name for uniqueness and drop the uniqueness constraint on e-mail address.
> ```

+1, currently, we do not support FAS account name changes anyway.

> We could be more diligent about checking up on FAS data and refreshing it from time to time, so that we would know when users do things like changing their e-mail address.

+1

Should I just go ahead and ask someone to fix my old account email?

thank you :)

**Comment by bowlofeggs** [comment]
On Wed, 2016-10-05 at 20:29 -0700, Athos Ribeiro wrote:

> Should I just go ahead and ask someone to fix my old account email?

Yes, I'd suggest asking in #fedora-admin.

**Comment by bowlofeggs** [comment]
@athos-ribeiro I have fixed your ribeiro account in Bodhi's database to have the same e-mail address that the account has in FAS. You should now be able to login to Bodhi with your new account.

Additionally, I believe that fixing https://github.com/fedora-infra/bodhi/issues/902 would allow users to self-service with this problem in the future. Bodhi should update its local copy of users' e-mail addresses upon login from FAS, but it does not currently do that.
