### ISSUE TITLE
Bodhi and Koji out of sync

### ISSUE THREAD

**Issue by ellert** [fedora-infra/bodhi#1089]
The update https://bodhi.fedoraproject.org/updates/FEDORA-2016-d19503aefa was ejected from the push to EPEL 7 testing.

Bodhi claims the update is in pending state.

The update contains 2 builds. Koji says the two builds are in different states:

$ koji list-tags --build=nordugrid-arc-doc-2.0.11-1.fc23
f23-updates-testing
$ koji list-tags --build=nordugrid-arc-5.2.0-1.fc23
f23-updates-candidate

**Comment by bowlofeggs** [comment]
Hello @ellert!

I spent some time today poking around in the database to see if I could tell what is happening with that update. I believe that whatever happened to it is resolved now, perhaps since it has been sent back to testing? When I look at the Build states, they seem correct to me currently.

I apologize that it took me so long to get to this, but I was out on vacation. I wish I'd seen it when it was in the broken state. I'm not sure what would have caused that to happen, but I think your update will work now. Please reopen this if you hit this problem again and hopefully I'll be able to see it sooner!
