### ISSUE TITLE
[RFE] export logs from bodhi for public debugging

### ISSUE THREAD

**Issue by dustymabe** [fedora-infra/bodhi#1138]
Would be nice to have these so people who aren't blessed with access to the infrastructure can try to help debugging like we can with pungi: http://kojipkgs.fedoraproject.org/compose/twoweek/Fedora-Atomic-25-20161130.1

nirik says: "it already writes out mash files to https://kojipkgs.fedoraproject.org/mash/updates/ it could write logs there too" 

thoughts?

**Comment by bowlofeggs** [comment]
My initial reaction is that I'm on the fence. I've seen several security flaws in the past due to programs accidentally logging secret information (even passwords in some programs!). Though I've not seen Bodhi do this, keep in mind that Bodhi's dependencies also get logged by Bodhi's logger so that's a lot of log statements to continuously audit.

**Comment by bowlofeggs** [comment]
During today's bodhi-stakeholder's meeting, we agreed that we would make the mash and ostree logs public.

**Comment by ausil** [comment]
mash and ostree logs being public can help people see what is going wrong in composes, and help debug issues. mash logs for instance can help people figure out why a package is multilibbed

**Comment by bowlofeggs** [comment]
@puiterwijk published the logs at https://kojipkgs.fedoraproject.org/mash/atomic-updates-logs/
