### ISSUE TITLE
The releases graph is undiscernable for releases that have a long history, like EPEL 6

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1172]
The EPEL 6 releases graph has far too many dates on the X-axis to be useful:

https://bodhi.fedoraproject.org/releases/EL-6

We probably need some code to decide how many dates to include there so it doesn't get too crazy. I'm going to assume this is HTML/JS/CSS work and that it's easy, but I could be wrong.

**Comment by cbdavide** [comment]
Hi, I've been looking around the code, and searching the Internet, and I've come with a few solutions:
- (trivial) Wrap the canvas in a container and through CSS implement a scroll bar to see the chart in a more comfortable way. This approach has some downsides, like the y-axis and its values will not be fixed to a static position, and the start position of the viewer is going to be at the oldest dates.
- Update the version of ChartJS, in order to use some new features, like animations to implement a x-axis scroll, like in this [example](http://jsfiddle.net/jmpxgufu/), with this approach the y-axis and its values will be fixed to a static position and I think that the position of the viewer will be at the most recent dates.
- Sort the data to create slides per year, but I'm not entirely sure how to do that because I don't understand what's the logic of the datasets  ...so I would think it would be better to inject the data in the template in other way, to facilitate this approach.

Tell me what do you think about it.

**Comment by bowlofeggs** [comment]
Those all sound pretty fancy, but also like they might be a lot of work. Perhaps a simpler solution would be to reduce the granularity of the data, i.e., drop some data points so that there are only as many as can be comfortably graphed. For example, say only 10 data points can fit in there nicely, but we have 100. A simple solution would be to only include one out of 10 data points (keeping 0, 10, 20, 30, etc.), throwing the rest away.

**Comment by cbdavide** [comment]
I believe this piece of code should do the work:
```javascript
let ratio = data.labels.length > 19 ? 11 : 6
let module = Math.round(data.labels.length / ratio)

let filter = function(arr, r) {
    let i = 0;
    return arr.filter(element => {
        return ((i++) % r === 0)
    })
}

data.labels = filter(data.labels, module)

for(let dataset of data.datasets) {
    dataset.data = filter(dataset.data, module)
}
```
It keeps the ratio of data points in an amount that is comfortably grafted to a maximum of 11-13 data points.
