### ISSUE TITLE
Problem retriving updates

### ISSUE THREAD

**Issue by Fale** [fedora-infra/bodhi#1177]
Giving:
```
bodhi -m
```

Returns a bunch of udpates (not all of them) and then:
```
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 411, in main
    log.info(data['title'])
KeyError: 'title'
```

**Comment by bowlofeggs** [comment]
Hello @Fale!

Thanks for the bug report! It sounds like this is for bodhi-0.9 (I'm guessing since /usr/bin/bodhi is autogenerated in bodhi 2). I don't mind at all that you filed this here (in fact I appreciate bug reports no matter how they arrive!), but I prefer to use GitHub to track issues in Bodhi 2's codebase and Bugzilla to track issues with packaging and/or bodhi-0.9's codebase. It turns out there's already a BZ there about this:

https://bugzilla.redhat.com/show_bug.cgi?id=1259681

It also turns out that that BZ links to another GitHub issue about this too:

https://github.com/fedora-infra/bodhi/issues/810

I will close this issue so we can track the issue in BZ. As I mentioned in one of the comments there, it is difficult for me to find the time to fix many bodhi-0.9 bugs (though I have fixed one so far!) so I can't promise I'll be able to fix this one before F25 goes EOL ☹
