### ISSUE TITLE
Use pungi to build OSTrees

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1182]
Currently Bodhi builds OSTrees in its masher. This results in OSTree being built only for the architecture that Bodhi's masher runs on (x86_64).

We should instead use koji runroot to build OSTrees in Koji so that we can support the variety of architectures that Fedora otherwise supports. It has been suggested that we may be able to use pungi to do this.

**Comment by ausil** [comment]
https://pagure.io/releng/blob/master/f/scripts/build-test-ostree is an axample where we use the pungi code in the chroot to do ostrees, however you might be able to more easily do things by importing pungi and using its apis

**Comment by dustymabe** [comment]
had a long chat with dgilmore and kushal about this today.

Basically the steps to call pungi from bodhi are:

- clone pungi-fedora git repo with the configs
    - we'll be using a config like https://pagure.io/pungi-fedora/blob/f26/f/fedora-atomic.conf
- update comps and put comps in place
    - we can re-use comps from bodhi process
    - we just need to either point pungi at the existing location, or copy the comps file into the location with the pungi config
- update bodhi repos in the config file
    - basically inject the repo locations into fedora-atomic.conf
- call pungi with a command like
    - `pungi-koji --notification-script=/usr/bin/pungi-fedmsg-notification --config=$CONFIG`

We have a few other requirements for this work at this point:

- We have to make sure that we block bodhi finishing until the pungi run is complete to keep functionality the same as it is today.
- We can only test this code in "production", so for now we will keep old branches (f25,f24) using the old code, and special case in the new code for f26

I will work with releng to make a pungi config we can use for this. Kushal is working on finishing up the bodhi code work. Hopefully we'll have something very soon we can get into a release and test out.

**Comment by dustymabe** [comment]
one open question we had was `how do we tell pungi to use the repo bodhi just mashed?`. It turns out we can just use the url like `https://kojipkgs.fedoraproject.org/mash//updates/f25-updates-testing-170425.2246/` and immediately have access to the mashed content. This means all we have to do is use that url and poke it into the pungi config.

I think we can do this by adding an entry to `source_repo_from` (and making it a list) like is done [here](https://pagure.io/pungi-fedora/blob/f25/f/fedora-atomic.conf#_261). @ausil, can you confirm that we can add the url to `source_repo_from` and it will get picked up by ostree generation?

**Comment by dustymabe** [comment]
any updates on this?
