### ISSUE TITLE
Add issue and Pull Request template

### ISSUE THREAD

**Issue by ankit01ojha** [fedora-infra/bodhi#1344]
It would be nice if we have a issue and pull request template so that the standard of the issues and pull requests can be maintained.

**Comment by ankit01ojha** [comment]
@bowlofeggs If you think its a good idea then I can work on this.

**Comment by trishnaguha** [comment]
Where would you like to have the issue and pull request template? and What issue and Pull request you are talking about?

**Comment by ankit01ojha** [comment]
When we will click the new issue button then it will come in the box and when the pull request is made then in that box.

**Comment by bowlofeggs** [comment]
I don't think we have a problem with how people file issues or pull requests currently that would warrant the need for a template. To be honest, I often find that templates encourage people to file extraneous information that isn't necessarily relevant to the issue they are filing about, which makes it more difficult to find the important information. I'm satisfied with the quality of 95% of the issues I see filed, and most of the time the original submitter is responsive when I have clarification questions. I'd much rather let the submitter think about what information is relevant for me to know.

We also have contributor guidelines that document what is expected of pull requests:

https://bodhi.stg.fedoraproject.org/docs/developer_docs.html#contribution-guidelines

Lastly, we will probably not remain on GitHub in the long term since it is closed source, so I'd rather not expend efforts on integrating further with it.

Thank you for the suggestion, and for your understanding!
