### ISSUE TITLE
Bodhi documentation build failed and unavailable

### ISSUE THREAD

**Issue by it-praktyk** [fedora-infra/bodhi#1390]
The documentation for Bodhi last time was build successfully on [March 9, 2017. 1:26 p.m.](https://readthedocs.org/projects/bodhi/builds/5127956/).

The link in README.md is broken.
![selection_003](https://cloud.githubusercontent.com/assets/4910261/24470654/9c0c2550-14b7-11e7-9822-f3920984f522.jpg)

**Comment by bowlofeggs** [comment]
Thanks for the bug report @it-praktyk!

The docs will soon be hosted at that URL, but due to a Fedora infrastructure freeze that has gone longer than I expected, I am not currently allowed to make the required change to production to host the docs there. We actually just recently merged a PR that put that link in the Readme under the assumption that the link would go live sooner than this. However, rest assured that the link will go live whenever the current infrastructure freeze is over.

In the meantime, the docs are available at https://bodhi.stg.fedoraproject.org/docs. It could be worth updating the readme to link there, but we'd be changing it back whenever the freeze is over.

Also, we will no longer use Read the Docs once the freeze is over and the docs are hosted at their new home.
