### ISSUE TITLE
Split the Update model into two

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1394]
We need to split the Update model into two models, a superclass (probably still called Update) and a new RPM-specific subclass, perhaps simply called RPMUpdate. All of Update's relationships should be analyzed to determine which ones should be adjusted to reference RPM vs. continuing to reference Update. Also, a database migration will be needed so that Bodhi's existing data can be preserved in the new split Update design. All code will need to be altered to use the new RPM model rather than the Update model when the data involved is RPM-specific.

Once this is done, all of Bodhi's functionality should continue to work exactly as it does today.

**Comment by jeremycline** [comment]
So I've taken a survey of the Update model (and written docs in #1445), and I think we can get away without having a special update type for each content type. An Update can know its type(s) based on the builds it's composed of, since builds have types.

There's a single catch I know of which is a problem we have to handle whether or not we have type-specific Update models. At the moment, bodhi has [a utility](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/util.py#L199) that gets all the packages marked critical path, but this only applies to RPM (I think? The [pkgdb2-cli](https://pagure.io/pkgdb-cli/blob/master/f/pkgdb2client/__init__.py#_348) seems to hit [the critpath API](https://admin.fedoraproject.org/pkgdb/api/#critical_path_packages) and that makes no mention of namespaces) so that's probably something we need to address first).

**Comment by bowlofeggs** [comment]
Your conclusion sounds reasonable to me. Should we use this ticket to add code to enforce that an ```Update``` only has one type of ```Build``` associated with it through a validator (or any other way that makes sense)? If we did something like that, would we need to also add a validator to the other end of the relationship (i.e., the ```Build```) so that the other end can't link to an ```Update``` that has other types? I presume that sqlalchemy validators don't validate from both ends if only defined on one end, but I could be wrong.

**Comment by bowlofeggs** [comment]
As for the critical path packages, I think it would be reasonable for Bodhi to assume for now that only RpmPackages can be critpath. We can watch pkgdb's progress and when its API gains the ability to make other types be critical path we can revisit our code.

It would be good to file a Bodhi issue about this, so I'll do that now.

**Comment by bowlofeggs** [comment]
I filed #1448 to track the critical path problem you mentioned here.
