### ISSUE TITLE
Blank dark-gray banner at the top of screen in chrome

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/bodhi#1424]
![](http://threebean.org/img/bodhi-banner.png)

It only shows up for me in chrome, but not firefox.

/cc @ryanlerch

**Comment by bowlofeggs** [comment]
I think this is just due to browser caching of some of the old UI files - try CTRL-F5 to force a cacheless reload. Please reopen if that doesn't fix it!

**Comment by bowlofeggs** [comment]
@puiterwijk suggested adding a ```GET``` parameter that would be unique per static file to the static file URLs so that new Bodhi deployments would cause browser caches not to be used.

We could just add a ```?bodhi_version={bodhi_version}``` onto the static URLs so that when we deploy new Bodhi versions the users will not used cached versions of all the static files. This would mean that we would get a bit more load on the server after each release, but that's probably OK because it would automatically solve this problem for future changes too.

**Comment by mattiaverga** [comment]
I had a look at #1464 and to @bowlofeggs comment about modify `request.static_url()`.
From Pyramid docs it seems the recommended way would be adding a new method to `request` with the `add_request()` method and then use the new method in the template in place of `${request.static_url()}`.
That means modify all the template files to use the new method.

I would instead propose to modify https://github.com/fedora-infra/bodhi/blob/ed53abdda445216708f80ede6c6ea9d8c4bb1d47/bodhi/server/__init__.py#L257
to something like
`config.add_static_view(f'static/{bodhi.util.version()}', 'bodhi:server/static')`
so that with a single change we get all static files served under a versioned directory like `static/4.0.2/`, thus solving the browser cache problem after a bodhi upgrade.

It seems acceptable to you?

**Comment by bowlofeggs** [comment]
On Mon, 2019-06-17 at 11:32 -0700, Mattia Verga wrote:
> It seems acceptable to you?

Putting the Bodhi version into the static URL does seem like a good way
to solve that problem. @puiterwijk has suggested that before as well.
