### ISSUE TITLE
Bodhi should show a lock icon next to the status if all of the builds in an update are signed

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1469]
I believe that Bodhi's old UI had a set of lock/gear icons to indicate whether all the builds in the update were signed yet or not. The new UI does show whether individual builds are signed in the Builds tab, but it doesn't appear to show the overall signature status of the update anymore. I believe the Update model does have a signed attribute, so it should be pretty straightforward to include the icons for the overall update state, perhaps next to the "status" bit on the main tab.

**Comment by ryanlerch** [comment]
IIRC, we use the lock icon at the moment to show if an update is locked, so we will probably want to avoid using the lock again here. (unless we can come up with something better for that).

Going through the FontAwesome icons (the ones we now use in Bodhi), the only one that jumped out at me for this purpose was the key (http://fontawesome.io/icon/key/), since the updates are signed with an encryption key. But open to suggestions here on a better one.

**Comment by bowlofeggs** [comment]
On Mon, 2017-04-24 at 14:29 -0700, Ryan Lerch wrote:
> Going through the FontAwesome icons (the ones we now use in Bodhi),
> the only one that jumped out at me for this purpose was the key (http
> ://fontawesome.io/icon/key/), since the updates are signed with an
> encryption key. But open to suggestions here on a better one.

Ah good point. The key sounds good to me. We should also change the
icon to the key on the builds tab.

**Comment by ryanlerch** [comment]
Just a note too, we currently do show the cog (which is used to signify that the update is being signed) next to the request status of the update, but we don't show the lock.

IMHO, this should be both next to the status, rather than the status request, right?
