### ISSUE TITLE
The fedmsg_enabled setting can't be set to False

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1488]
If the settings file has ```fedmsg_enabled = False```, fedmsg will still be enabled. This is because the setting is used like this:

```
bodhi.server.config.config.get('fedmsg_enabled')
```

There are two places that this setting is used:

https://github.com/fedora-infra/bodhi/blob/2.6.0/bodhi/server/notifications.py#L33
https://github.com/fedora-infra/bodhi/blob/2.6.0/bodhi/server/notifications.py#L93

**Comment by areyohrahul** [comment]
@bowlofeggs Hi, I am Rahul and I am new to this community. Since this is an easy bug so I would like to take this up. Can you please let me know what do I exactly have to do here? Thanks.

**Comment by ralphbean** [comment]
oh, @mcurlej - if you're looking at this one, also see #1544.  There, @bowlofeggs is refactoring the whole config system, and it may indirectly fix this issue.

**Comment by bowlofeggs** [comment]
Hi @rahulxxarora,

As @ralphbean mentioned, I've already fixed this issue in #1544. There are several other open easy fix issues to take on!

**Comment by mcurlej** [comment]
@bowlofeggs @ralphbean k will find another one.

**Comment by surya-prakash-susarla** [comment]
Can anyone help me get started with solving some simple bugs ??

**Comment by bowlofeggs** [comment]
On Sat, 2017-06-03 at 04:55 -0700, Surya Prakash Susarla wrote:
> Can anyone help me get started with solving some simple bugs ??

Hello Surya,

This issue is already fixed by an open pull request - I recommend
finding another unassigned Easyfix issue.

**Comment by surya-prakash-susarla** [comment]
Thanks four the update could you help me with some other questions also?

On 4 Jun 2017 00:58, "Randy Barlow" <notifications@github.com> wrote:

On Sat, 2017-06-03 at 04:55 -0700, Surya Prakash Susarla wrote:
> Can anyone help me get started with solving some simple bugs ??

Hello Surya,

This issue is already fixed by an open pull request - I recommend
finding another unassigned Easyfix issue.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/fedora-infra/bodhi/issues/1488#issuecomment-305996298>,
or mute the thread
