### ISSUE TITLE
Create a fedmsg-client to update test gating status on new Greenwave decisions

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#1513]
We need a fedmsg-client to listen to CI messages and update the corresponding bodhi update (if there are any corresponding to this commit).

**Comment by bowlofeggs** [comment]
This is blocked on us knowing what fedmsgs will come and from where for the various ci statuses. We need "something" to send messages on these events:

0. The build will not be tested (skipped).
1. The build is queued for testing.
2. The build is currently being tested.
3. The tests passed.
4. The tests failed.

Do we know what will provide these various messages? Will they all come from Greenwave, or will some come from it and others from elsewhere?

**Comment by bowlofeggs** [comment]
CC @ralphbean Do you have answers to my above question, and answers for any other problems I may encounter in life?

**Comment by pypingou** [comment]
> The build will not be tested (skipped).
> The build is queued for testing.
> The build is currently being tested.

I think these three will come from the CI system, I am not sure if taskotron sends messages when it starts testing an update, would be worth checking.

The other two will be also sent by the CI system but we should ignore them and just act on the messages from greenwave

**Comment by bowlofeggs** [comment]
@pypingou Cool, that sounds reasonable to me. I have a few follow up questions that we'll want to answer in order to get started on coding:

1. What will the message topics be for the various messages?
2. Similarly, what will the message schema be?

It's tricky to get started with coding unless we know those things. Is CI running anywhere yet that we can see real messages? If it were, that would help me get started on this.

Technically, we can go without this if we do #1515, since that one will get us "eventual consistency" so I guess it is an option to delay fixing this issue until we have CI in place so we have real data to code against. Maybe that wouldn't be a bad way to go?

**Comment by bowlofeggs** [comment]
@ralphbean Will Greenwave be emitting fedmsgs as tests pass, or does Greenwave only react to web requests? I.e., is it "passive" or "active", if that makes sense?

**Comment by pypingou** [comment]
> What will the message topics be for the various messages?
> Similarly, what will the message schema be?

The end part of the topic as well as the structure is defined at: https://github.com/CentOS-PaaS-SIG/ci-pipeline/#message-bus if something change we should report it to them but I think that's what I based my work on and it worked :)

**Comment by bowlofeggs** [comment]
@pypingou great! OK I have one more question (sorry for so many) - where can we look up whether builds are skipped if we miss the fedmsgs?

**Comment by pypingou** [comment]
> where can we look up whether builds are skipped if we miss the fedmsgs?

Currently it's in ccsdb, but ultimately this should be in resultsdb as well

**Comment by bowlofeggs** [comment]
This is blocked by https://pagure.io/greenwave/issue/87.

**Comment by mikebonnet** [comment]
For reference, https://pagure.io/greenwave/issue/87 was completed at the end of October.
