### ISSUE TITLE
Cron job update CI status in addition to fedmsg

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#1515]
We would like a cron job that would be checking and updating the CI status of all the updates for which we are missing this information.

This would help mitigate potential network issues (ie: missed fedmsg message)

**Comment by bowlofeggs** [comment]
This depends on #1499, and the commit hash patch that I've been working on depends on this.

**Comment by bowlofeggs** [comment]
We plan to use [Greenwave](https://pagure.io/greenwave) as the "source of truth" for whether updates pass CI tests. There is [one issue](https://pagure.io/greenwave/issue/26) that blocks work on this ticket. Also, since the [Greenwave response's schema is undocumented](https://pagure.io/greenwave/issue/25), I am including a link to a demo that shows an example call/response or two:

https://fedorapeople.org/groups/factory2/sprint-033/dcallagh-greenwave-multiple-products.ogv

**Comment by bowlofeggs** [comment]
The CI status feature got removed recently.
