### ISSUE TITLE
Any logged in user can create or expire a buildroot override for any package

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#1594]
Currently, any logged in user is able to create a buildroot override for any package. AFAICT, we don't check any ACLs from packageDB when doing buildroot overrides. Note too that this also allows any logged in user to expire a buildroot override that someone else has created.

The only reason why the non-logged in user couldnt create a buildroot override was due to the exception raised in #1541

**Comment by bowlofeggs** [comment]
I do believe that due to your recent fix, Bodhi does now enforce that the user be a packager (i.e., not just logged in but also a member of a packager group).

I think the permissions might be intentionally this way. A lot of packagers depend on packages that they don't have ACLs on, and they may need to build their packages against a version of a dependency that isn't yet stable. Allowing them to create a BuildrootOverride for those packages gives them a "self service" option, rather than having to ask the package maintainer to do it for them. It's probably a bit of an unfortunate side effect that packagers can expire other user's overrides, but I haven't seen people doing that maliciously so far. We *could* do something special to disallow that, but I would probably recommend waiting until it's a real problem before doing that.
