### ISSUE TITLE
libravatar.org, CSRF verification failed

### ISSUE THREAD

**Issue by c72578** [fedora-infra/bodhi#1674]
How to reproduce:
https://bodhi.fedoraproject.org/
Login 
Your Profile
Click on your avatar picture
https://www.libravatar.org/openid/login/

The following error appears:
Forbidden (403)
CSRF verification failed. Request aborted.

How reproducible: always

Version: Running bodhi-2.8.1 on bodhi04.phx2.fedoraproject.org

**Comment by bowlofeggs** [comment]
We probably need to use a different URL on that link. Thanks for the report!

**Comment by ryanlerch** [comment]
IMHO, the best thing here is to probably just remove the link altogether to libravatar (for now).

Just dropping the user to libravatar without any explaination is probably not the best thing. We might want to add a link that points to a Fedora Wikipage or Doc that explains how to change your avatar.

But to fix this issue, i think the best bet is to just remove the broken link.

**Comment by ryanlerch** [comment]
On second thought, we could probably just remove the POST request here to libravatar.org, and just do a link to https://www.libravatar.org/openid/login/?openid_identifier=dudemcpants.id.fedoraproject.org.

It fills out the form, ready for the user to login.

**Comment by bowlofeggs** [comment]
The patch for this issue should be included in the upcoming 2.10.0 release:

https://github.com/fedora-infra/bodhi/pull/1744

**Comment by ghost** [comment]
Hello, I have the same issue now.

How reproduce

* https://badges.fedoraproject.org/
* Login
* Change avatar
* Forbidden (403)

CSRF verification failed. Request aborted.

You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests.

More information is available with DEBUG=True.

regards!

**Comment by bowlofeggs** [comment]
@carlosm0rel If you are experiencing this in the badges app, I recommend you report the issue there:

https://github.com/fedora-infra/tahrir/issues
