### ISSUE TITLE
Can't push update to stable (days to stable is below zero)

### ISSUE THREAD

**Issue by tpopela** [fedora-infra/bodhi#1708]
Hi,

can someone please look at why I was not able to push https://bodhi.fedoraproject.org/updates/webkitgtk4-2.16.5-1.fc24 to stable? There was only Unpush button available and autopush enabled. Could it be related to the "days to stable" that is -13?

I had to ask a colleague to provide a karma to trigger autopush in the end.

**Comment by bowlofeggs** [comment]
Hello @tpopela,

I was able to use last night's database dump to see the state of the update and figure out what happened. There are a couple of separate bugs here actually, though I think only one of them explains why you were unable to push.

The big problem is that karma is not being counted correctly for critical path updates in the [```meets_testing_requirements()```](https://github.com/fedora-infra/bodhi/blob/2.8.1/bodhi/server/models.py#L2451-L2457) method. That method is using ```self.comments``` instead of using ```self.comments_since_karma_reset```. Because of this, that user that gave you a -1 is still counting against you, even though you have since added a new build (which reset the karma). Furthermore, there's an even easier way it could do this - it could just use ```self._composite_karma``` to get a count of -1's and share code (and that method already does it the right way). So that should actually be pretty easy to fix.

The other problem is that the [```days_to_stable()```](https://github.com/fedora-infra/bodhi/blob/2.8.1/bodhi/server/models.py#L2506-L2509) method can return a negative number if ```meets_testing_requirements()``` returns ```False``` (as it did in this case). We should rework that to only return the value if it is > 0, else return 0. That should also be pretty easy to fix.

**Comment by bowlofeggs** [comment]
The fix for this issue will appear in the upcoming 2.11.0 release:

https://github.com/fedora-infra/bodhi/pull/1790
