### ISSUE TITLE
Broken link to database schema in developer docs

### ISSUE THREAD

**Issue by jarifibrahim** [fedora-infra/bodhi#1717]
The link to the image file on developer docs page[0] is broken.

[0] - https://github.com/fedora-infra/bodhi/blob/develop/docs/developer_docs.rst#database-schema

**Comment by jeremycline** [comment]
Hi @jarifibrahim, thanks for the report!

The image is generated as part of the documentation build process - if you want to see it locally you can use the ``Makefile`` in the docs, or you can [see it live](https://bodhi.fedoraproject.org/docs/developer_docs.html#database-schema).

**Comment by jarifibrahim** [comment]
@jeremycline The docs page on Github points to an image of the database schema that does not exist. Shouldn't it be fixed?

**Comment by jeremycline** [comment]
@jarifibrahim The documentation is not intended to be read on GitHub - it's merely a place to store the sources used to build the documentation. Rather than check the binary image into git, it's generated when the HTML is generated from the RST.  The built documentation is hosted with Bodhi ([for example, Fedora's deployment](https://bodhi.fedoraproject.org/docs/)) and, as you can see, the image is present.

**Comment by jarifibrahim** [comment]
@jeremycline Right. Thanks!
