### ISSUE TITLE
The link to Fedora Flavored Markdown is "smashed" on mobile

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#1791]
I noticed that the link to "Fedora Flavored Markdown" is "smashed" when viewing it on my phone:

![screenshot_20170902-180831](https://user-images.githubusercontent.com/354506/30131006-293546e8-9319-11e7-9a60-7bf4da0df14a.png)

Do not let my very low battery concern you!

**Comment by bowlofeggs** [comment]
Note also that the "Auto-request stable" and "Stable karma" inputs are misaligned with the rest of the form they are part of.

**Comment by ryanlerch** [comment]
yeah something funky is going on with the boostrap grid here, likely caused by a poor use of rows and cols in our template. note too that at smaller sizes, a dark grey bar appears at the top of the page:

![screen shot 2017-09-14 at 10 55 49](https://user-images.githubusercontent.com/592259/30407451-a23e9710-993b-11e7-8d37-beca44bd5f0e.png)

**Comment by bowlofeggs** [comment]
This patch is included in the bodhi-3.1.0-0.1.beta, which is deployed to [staging](https://bodhi.stg.fedoraproject.org/) and is also available via [Copr](https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/).
