### ISSUE TITLE
If a new build obsoletes a security update it should also be a security update

### ISSUE THREAD

**Issue by nullr0ute** [fedora-infra/bodhi#1798]
A maintainer might submit a new build of a package that fixes a bug so will label the update a bugfix, but if it's obsoleteing a security update the new update should also be a security update.

eg: firefox from  firefox-55.0-6.fc26 ->  firefox-55.0.1-1.fc26

https://bodhi.fedoraproject.org/updates/?packages=firefox

**Comment by pmatilai** [comment]
Just encountered this with rpm, a co-maintainer submitted an enhancement update without realizing there's an security update pending, and bodhi silently auto-obsoleted the security update with the enhancement one. And since the update can't be edited anymore, the rather critical security rating of the original update got *silently* lost in the process. This is rather terrible.

Auto-obsoleting with no questions asked seems highly questionable even with other types of updates, but in case of security updates it's even worse.

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in Bodhi 3.13: #2917.

**Comment by bowlofeggs** [comment]
This feature is now deployed to staging: https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

It is also available via Copr: https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/

**Comment by bowlofeggs** [comment]
Bodhi 3.13.0 has been released:

https://github.com/fedora-infra/bodhi/releases/tag/3.13.0

Fedora Infrastructure plans to deploy it to production on Monday.
