### ISSUE TITLE
RFE: Packager can choose autopush for updates 

### ISSUE THREAD

**Issue by zdohnal** [fedora-infra/bodhi#1803]
Hi,
some updates (for older releases mainly) don't get enough karma to be submitted to stable in several days and they need to be submitted to stable manually by packager. Would you mind adding option like "submit to stable after 7 days in testing"? I know it should be able to solve it by lesser karma, but IMO it is more dangerous.

**Comment by keszybz** [comment]
FWIW, I think this doesn't need to be a separate option. I think that if somebody submits an update with autopush enabled, this means "push when the criteria are satisfied", and it doesn't really matter if the karma or time is reached first.

**Comment by mattiaverga** [comment]
> FWIW, I think this doesn't need to be a separate option. I think that if somebody submits an update with autopush enabled, this means "push when the criteria are satisfied", and it doesn't really matter if the karma or time is reached first.

I don't agree. For example, I may want to push automatically an update only if karma threshold is reached or choose myself to manually push it.
I think a separate option would be better.

**Comment by bowlofeggs** [comment]
I am currently working on drafting a new update policy for Fedora, and one the elements I plan to include in the proposal is automatic pushing unless humans stop it (via negative karma or maintainer unpushing). I recommend holding off on implementing this until I can draft said policy and get approval from FESCo, so we know what policy to implement based on FESCo's decision.

**Comment by c72578** [comment]
An option like "submit to stable after x days in testing" would help e.g. in the following case:
- An updated package "foo" is submitted to updates
- A few days later, within the testing phase, it turns out, that a different package "bar" needs to be rebuilt because of the updated package "foo" (this can happen). Using a buildroot override in the meantime.
- Both packages "foo" and "bar" can be pushed then at the same time, so that they arrive the same time in updates. And package "bar" will work, because it was rebuilt. And package "foo" did not arrive too early in updates, breaking "bar".

**Comment by keszybz** [comment]
@c72578 First of all, in this situation the two packages should have right Requires and Conflicts, so the package manager refuses to upgrade or install packages that would break on of them. Second, those two packages should be put in the same update, so the user never sees the situation where just one packages is available in updates. Trying to achieve the same by pushing them at the same time is an inadequate and unnecessary solution.

**Comment by sebwoj** [comment]
Is it related to #3090?

**Comment by sebwoj** [comment]
@cverna What do you think?

**Comment by keszybz** [comment]
This has been implemented, so the ticket can be closed.
