### ISSUE TITLE
Confused new update created from bodhi CLI

### ISSUE THREAD

**Issue by tkdchen** [fedora-infra/bodhi#1928]
I use this command to create an update

```
bodhi updates new --user cqi --close-bugs --request testing --type enhancement --bugs 1188634 --notes "..." rpkg-1.51-1.fc27 fedpkg-1.30-1.fc27
```

output is

```
================================================================================
     rpkg-1.51-1.fc27 fedpkg-1.30-1.fc27
================================================================================
   Update ID: FEDORA-2017-9cac2b8b4a
Content Type: rpm
     Release: Fedora 27
      Status: pending
        Type: enhancement
       Karma: 0
   Autokarma: False  [-3, 3]
     Request: testing
        Bugs: 1188634 - None
       Notes: - ...
   Submitter: cqi
   Submitted: 2017-10-24 08:40:52
    Comments: bodhi - 2017-10-24 08:40:52 (karma 0)
              This update has been submitted for testing by cqi.

  https://bodhi.fedoraproject.org/updates/FEDORA-2017-9cac2b8b4a
```

Looks everything is good. But, in Bodhi website, the update type is ``security`` and both ``Auto-request stable?`` and ``closed bugs`` is not checked.

I have corrected my update. I'm not sure whether you can see the very original value of this update.

Version: ``bodhi-client-2.11.0-2.fc26.noarch``

**Comment by tkdchen** [comment]
Create another update, screenshot shows that.

![screenshot-2017-10-24 fedora-2017-ea72793352 security update for fedpkg and rpkg fedora updates system](https://user-images.githubusercontent.com/919706/31933788-b9233fce-b8dc-11e7-8517-0629a4660a00.png)

**Comment by tkdchen** [comment]
Interesting. Run above bodhi command to create update for Fedora 25, the third time, type is set to ``enhancement`` correctly.

![screenshot-2017-10-24 fedora-2017-f5ad4107cc enhancement update for fedpkg and rpkg fedora updates system](https://user-images.githubusercontent.com/919706/31934049-927ddfc2-b8dd-11e7-9b4e-aa353eee39a5.png)

But, after saving the changes to ``close bugs`` and ``auto push``, the type becomes ``security``.

**Comment by tkdchen** [comment]
> But, after saving the changes to close bugs and auto push, the type becomes security.

I think I know why this happens. When I run bodhi CLI last time to create update, update type is enhancement, but when I click Edit button in WebUI, ``security`` is checked in edit page. I didn't notice this when I was correcting my update.

**Comment by bowlofeggs** [comment]
I think there are a few different things going on here:

* When Bodhi detects that an update is associated with a BZ that is marked as a security bug, it automatically switches the update to a security update. [#1188634](https://bugzilla.redhat.com/show_bug.cgi?id=1188634) has the Security keyword on it, so that's why Bodhi switched it to a security update. I would recommend changing it back to security since the bug is a security related bug.
* The autokarma is off by default - use the ```--autokarma``` CLI flag to turn it on.
* The ```--closed-bugs``` flag is known broken. I think it might actually currently just work backwards from what it should do, so try just leaving it off until https://github.com/fedora-infra/bodhi/issues/1818 is fixed.

With the exception of #1818, I think I've addressed the various issues you've mentioned here, so I will close this so we can track that one problem over there. Let me know if you think there are still other issues I didn't address!
