### ISSUE TITLE
Bodhi allows package downgrades in stable releases

### ISSUE THREAD

**Issue by robatino** [fedora-infra/bodhi#1942]
In the latest F26 stable push, dnf was downgraded from 2.7.5-1.fc26 ( https://bodhi.fedoraproject.org/updates/FEDORA-2017-d2e8fdf5d8 ) to 2.7.4-1.fc26 ( https://bodhi.fedoraproject.org/updates/FEDORA-2017-9f04c2c90f ). The higher version was pushed to stable first, and the lower version after.

Edit: Replaced second link with the correct F26 one.

**Comment by bowlofeggs** [comment]
Hello!

Small correction, but I think you meant to use https://bodhi.fedoraproject.org/updates/FEDORA-2017-9f04c2c90f for that second link (the F26 version instead of the F27 version).

I believe what happened here is due to one of the updates having multiple builds in it. Bodhi has a few open issues about not handling multi-build obsoletion correctly:

https://github.com/fedora-infra/bodhi/issues/512
https://github.com/fedora-infra/bodhi/issues/1254
https://github.com/fedora-infra/bodhi/issues/1266

I believe those cover this particular issue so I will close this as a duplicate. Please let me know if you don't think those issues cover this, and sorry for the confusion!
