### ISSUE TITLE
PDC queries take too long and cause Bodhi requests to time out

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2035]
[```get_critpath_components_from_pdc()```](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/util.py#L767-L798) is extremely slow. During some testing, @puiterwijk found that individual requests to PDC for f27 take 8-30 seconds, and there are 8 pages/8 requests. This is why the proxy server is timing out on Bodhi requests.

**Comment by AdamWill** [comment]
The lack of critpath data for F27 is a critical issue that's causing us (QA) a serious problem I can't get around: openQA is running almost no update tests for F27 updates, because none are marked as critpath. Only updates to packages on the openQA scheduler's own testing 'whitelist' (which is mainly FreeIPA-related packages) are being tested at present.
