### ISSUE TITLE
Have the developer docs moved? The existing link points to a 404

### ISSUE THREAD

**Issue by abhiramr** [fedora-infra/bodhi#2044]
"https://github.com/fedora-infra/bodhi/blob/develop/docs/developer_docs.rst" that the developer documentation links to, doesn't seem to exist.

**Comment by bowlofeggs** [comment]
Hello @abhiii5459!

They have, and I forgot to update the README - thanks for filing this.

They are now at https://github.com/fedora-infra/bodhi/tree/develop/docs/developer. Note that some links inside there won't work because they are Sphinx docs and GitHub doesn't render those fully.

You can also browse the rendered docs from the most recent release here: https://bodhi.fedoraproject.org/docs/developer_docs.html

**Comment by abhiramr** [comment]
Thanks @bowlofeggs ! Closing this :)

**Comment by bowlofeggs** [comment]
The patch for this will be included in the upcoming 3.2.0 release:

https://github.com/fedora-infra/bodhi/pull/2092
