### ISSUE TITLE
docs: No mention of "Push to Batched"

### ISSUE THREAD

**Issue by dhowells** [fedora-infra/bodhi#2081]
The Bodhi documentation, as is online here:

https://bodhi.fedoraproject.org/docs/

does not mention "Push to Batched" or what it does - at least in version 3.1.0.

**Comment by bowlofeggs** [comment]
Your timing is perfect, as I just wrote a PR a couple days ago to document Bodhi's states:

https://github.com/fedora-infra/bodhi/pull/2060

Fedora's Bodhi instance is also documented at:

https://fedoraproject.org/wiki/Bodhi#Package_States

I'm closing this since there's an open PR to address it, but feel free to review that PR and comment if you want any improvements!
