### ISSUE TITLE
Don't fail tests when there are no test results

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#2124]
Looking at : https://bodhi.fedoraproject.org/updates/FEDORA-2018-5f09642217 right now the update is marked as "Tests Failed" and looking at the test results tab it shows: "The update can not be pushed: no test results found".

This is likely a race-condition between the check script and the test systems. The check script asked for a decision while the test systems had not finished running so it found nothing.

Proposal:
- Do not change the gating status if greenwave reported that no test results were found, leave it as pending.

Follow up:
- Split the check policies script into two queries:
  - All updates pending for updates-testing having their test status set to pending or failed (no need to re-check update that passed, unless they were edited in which case we should re-set the gating status)
  - All updates pending for updates (stable) having their test status set to pending (no need to check failed updates since at that points update cannot be edited anymore (right?))
Together with #2121 this may help speed up the check policies script.

**Comment by bowlofeggs** [comment]
There isn't a machine-friendly way for Bodhi to know this. Greenwave just has a ```policies_satisfied``` boolean. The "no test results found" is part of the summary, which is intended for humans to consume. In order to fix this, we need Greenwave to have a machine friendly state in its decision to indicate that a decision isn't ready yet.

**Comment by pypingou** [comment]
WFM

**Comment by pypingou** [comment]
Cross-ref: https://pagure.io/greenwave/issue/114

**Comment by AdamWill** [comment]
@pypingou notes that if we flip the greenwave policy so that 'all tests absent' results in a 'good to go' decision, this problem will still exist, but kinda in reverse: bodhi might get a 'good to go' decision before the tests have run and cache it, then it'll still consider the update 'good to go' if some tests run and fail after that, up until the cached decision is refreshed (not sure on the details of the caching).

**Comment by pypingou** [comment]
> up until the cached decision is refreshed (not sure on the details of the caching).

The cron script runs every 6 hours for the moment (it's meant to be replaced/complemented by a fedmsg client)

**Comment by AdamWill** [comment]
Ah, I see, so it's not intended as a caching mechanism, it's just a problem of knowing when to update the decision. So, as I recall ralph's talk, the plan is for greenwave to send a fedmsg whenever the decision for something changes, yes? How far are we away from that?

**Comment by ralphbean** [comment]
@AdamWill - https://apps.fedoraproject.org/datagrepper/raw?category=greenwave&delta=127800&rows_per_page=1

> There isn't a machine-friendly way for Bodhi to know this.

@bowlofeggs - yeah, there is.  See my comment in the greenwave issue @pypingou linked.

```python
if any([requirement['type'] == 'test-result-missing' for requirement in data['unsatisfied_requirements']]):
   # stay pending...
```

**Comment by AdamWill** [comment]
@ralphbean yep, @mohanboddu just told me the greenwave fedmsgs are working now :) that should help this out, I think, @bowlofeggs ?

**Comment by bowlofeggs** [comment]
@AdamWill I think @ralphbean's code snippet will do the trick. I think the fedmsg consumer is orthogonal, because we will still want this cron job when we have the consumer (Bodhi does occasionally miss messages from time to time, so it's a belt and suspenders approach).

**Comment by AdamWill** [comment]
note, there are several issues with the fedmsgs at present: see [greenwave #122](https://pagure.io/greenwave/issue/122) and [greenwave #123](https://pagure.io/greenwave/issue/123).

**Comment by sebwoj** [comment]
@bowlofeggs Is it ready, or it will be after #3200?

**Comment by bowlofeggs** [comment]
@sebwoj yeah #3200 is going to add a Greenwave listener. We still need a way to tell the difference between "tests are running/waiting/expected" and "tests never ran, something went wrong" however.

**Comment by AdamWill** [comment]
The way we handle this currently is as follows:

* If resultsdb tells us that all expected tests are "queued" or "running", we will keep the update in "waiting" gating status until they're done
* If a test result is really *missing*, the update gating status will stay as "waiting" for two hours since the update was last modified. After that, the next time the gating status is updated, it will go to "failed".

I'm not sure we can do much better than this; we can't really leave the status as "waiting" *forever* if we have gating configured for a test but it hasn't run for some reason. It should go to "failed" at *some* point. Two hours is a somewhat arbitrary cutoff (I actually chose it as openQA tests usually *ought* to be done within two hours), but if we want to change that it's easy enough to do.

If there's nothing more to do here, I think we could close this ticket.

**Comment by ppisar** [comment]
> we can't really leave the status as "waiting" forever if we have gating configured for a test but it hasn't run for some reason.

Why not? It's an accurate description of the state.
If you need to terminate the waiting period for some reason, the please present the tests which are missing results as failed (or timed out).

The reporter is rightfully frustrated that Bodhi displays "Tests failed", but when he checks each test one by one, none of them is in failed state.

**Comment by AdamWill** [comment]
They are displayed that way. "Missing" tests appear in red on the automated tests pane. I can't find an example of this ATM, but believe me, they do.

**Comment by ppisar** [comment]
Then it's fine. Thanks.
