### ISSUE TITLE
timestamps for taskotron results seem to be off

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#217]
If I look at https://bodhi.fedoraproject.org/updates/perl-Test-Vars-0.007-1.fc23 at "Automated Test Results" section, I see all results with a timestamp "2 hours ago". However, if @tflink looks at it, he sees "in 6 hours". That doesn't seem right. I'm UTC+2, he's UTC-6. Probably not a coincidence :)

**Comment by voxik** [comment]
Can confirm ... I submitted my update 4 minutes ago, but the rpmlint was done already 2 hours ago according to bodhi.

**Comment by ralphbean** [comment]
We're using [moment.js](http://momentjs.com/) to handle that time rendering.. and we probably just need to pass it some timezone information so it knows what to do.  (i.e., we need to tell it that the timestamp we're passing it from taskotron is in UTC, otherwise it may assume that it is in the web client user's local TZ).

**Comment by kparal** [comment]
All the timestamps we use in Taskotron should be in UTC. If you find something that isn't, please tell us and we'll fix it. Also, if you retrieve timestamps from ResultsDB or elsewhere using API (or fedmsg in the future), they should include a timezone information. If they don't, tell us and we'll look at it. Thanks.
