### ISSUE TITLE
"no test results found" error, despite list of test results being displayed

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#2224]
I submitted two updates to fedora {f27,f26}-testing about 12 days ago:

- https://bodhi.fedoraproject.org/updates/FEDORA-2018-c455a245b0
- https://bodhi.fedoraproject.org/updates/FEDORA-2018-4d0e13ff51

Both are still blocked from being pushed to stable because "no test results found", but browsing the "Automated Tests" tab shows test results, and manually querying resultdb also shows that all tests were indeed run and all checks passed:

- <https://taskotron.fedoraproject.org/resultsdb/results?item:like=*golang-github-xtaci-smux-1.0.7-1.fc27*>
- <https://taskotron.fedoraproject.org/resultsdb/results?item:like=*golang-github-xtaci-smux-1.0.7-1.fc26*>

It looks like the "no test results found" status for those updates just wasn't updated once the test results were available.

**Comment by bowlofeggs** [comment]
The no test results found error is coming from Greenwave and Bodhi is just displaying it. I don't know why Greenwave is saying that there are no test results found, but I suggest filing an issue there:

https://pagure.io/greenwave/issues

In the meantime, I think it may now be possible to waive missing test results with waiverdb, so I recommend doing that in this case and moving along.

I'm going to close this issue since it's a problem in Greenwave. Thanks for the report!

**Comment by decathorpe** [comment]
Thanks for looking into this. I've opened an issue with greenwave [here](https://pagure.io/greenwave/issue/141), as you suggested.

**Comment by ralphbean** [comment]
As in [greenwave#141](https://pagure.io/greenwave/issue/141):

```bash
$ waiverdb-cli -p "fedora-27" -t dist.rpmdeplint -s '{"item": "golang-github-xtaci-smux-1.0.7-1.fc27", "type": "koji_build"}' -c "There really are no dist.rpmdeplint results for this in resultsdb at the moment."
```
