### ISSUE TITLE
[M] Investigation: Bodhi needs a way for packagers to re-request tests to be run

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2323]
In addition to waiving updates, we should offer a way for packagers to ask for tests to be re-run.

**Comment by bowlofeggs** [comment]
On Sun, 2018-12-02 at 19:04 +0100, @sebwoj wrote:
> I assume that solution can looks like "waiving" workflow, where someone is sending request to API(via CLI or UI) to bodhi, and then bodhi is changing 
> "test_gating_status" to "waiting" and talk to greenvaive to restart tests.

Yeah sort of, except that Greenwave doesn't restart the tests. There are a few different unrelated systems that run the tests (taskotron, openQA, and the CI pipeline), so we'll need to do some research to identify how to ask each of those systems to re-run tests.

**Comment by bowlofeggs** [comment]
We will use this card to track the work to research and plan the work needed to accomplish the task. This ticket is done when there are new issues filed for the work needed to accomplish the above.

**Comment by cverna** [comment]
Idea is to sent fedora-messaging message to each CI system to retrigger the tests, part of the investigation is to define the message body that needs to be sent.

**Comment by tdawson** [comment]
For Fedora OpenQA the topics that is is listening for is fairly straightforward
https://pagure.io/fedora-qa/fedora_openqa/blob/master/f/fedora_openqa/consumer.py#_205
  org.fedoraproject.{prod,stg,dev}.bodhi.update.request.testing
  org.fedoraproject.{prod,stg,dev}.bodhi.update.update.edit

The bodhi code that sends those messages, is also easy to find
  https://github.com/fedora-infra/bodhi/blob/develop/bodhi/messages/schemas/update.py#L246
  https://github.com/fedora-infra/bodhi/blob/develop/bodhi/messages/schemas/update.py#L450

As you said, what really had to be done is get the message right.  I'm still looking for OpenQA, but I'm hoping that since we know what Update/Compose the user is working on, it should just be a matter of calling a function, passing it that Update and/or Compose.

**Comment by tdawson** [comment]
Re-running tasks on Taskatron is harder than OpenQA.  In theory, this is done with Taskotron-trigger.  In practice, the code that is there is just a proof-of-concept, and Taskotron is currently in maintenance only mode.
I wrote to the current maintainers/developers, and got replies from Tim Flink and Josef Skladanka.

Tim let me know that Taskotron is in maintenance only mode, and due to be deprecated as soon as a replacement system is available.  He is unsure what that replacement will be called but welcomes feedback on how the interface should look and is "open to ideas/suggestions to keep in mind as the new system takes shape"

Josef replied with more technical details.
Currently there is Proof of Concept code for re-running Taskotron tasks.  This was written because of the missing messages problem of fedmsg.
https://pagure.io/taskotron/taskotron-trigger/blob/master/f/jobtriggers/taskotron_result_missing_msg.py
If this were to move from Proof of Concept, to real code, he would like to simplify it. 

> It could really, honestly, be simplified (?) if we decided to instead get ExecDB into the mix - each (taskotron) result coming from ResultsDB is also part of a group, and that group's UUID is the same as the Job's UUID in ExecDB, and ExecDB (IIRC) stores all the key-values needed to spin another job in Buildbot.
> The "please rerun test" message could then be boiled down to "here is an UUID (list of UUIDS?), please rerun these jobs".

This would require some coding for both the Trigger and ExecDB.  He gave an estimate of how much time it would take.

> I can get these both done in a matter of one work-day, building and rolling out the packages can take.. IDK how long, but a week at least once the changes are merged/accepted.

He ends with sentiments similar to Tim's

> ... also the fact that Taskotron is "officialy" supposed to just die in the infernal flames, and get replaced by something else (no binding schedule on the replacement, though, AFAIK).

So, in the end, it looks like code would be needed for both Bodhi and Taskotron, to allow users to easily re-run tasks on Taskotron.

**Comment by tdawson** [comment]
Re-running tests on Fedora-CI might be just a matter of re-sending the correct messages.
Just a few things about the Fedora-CI.
The actual testing get's run on CentOS-CI, which is jenkins based.
The code that triggers the tests is found here  https://github.com/CentOS-PaaS-SIG/upstream-fedora-pipeline
The current maintainers of that code are Miroslav Vadkerti  and Bruno Goncalves.
The messages that it is listening for have the topics
```
  org.fedoraproject.prod.buildsys.build.state.change
  org.fedoraproject.prod.buildsys.task.state.change
  org.fedoraproject.prod.pagure.pull-request.comment.added
  org.fedoraproject.prod.pagure.pull-request.new
  org.fedoraproject.prod.pungi.compose.status.change
```
If we are able to resend messages with those topics (at least the ones we care about), then we shouldn't need to change any code.  But, since we are bodhi, we might not be able to send messages with those topics.
If we were to send out own bodhi.retest messages, we'd have to do some tweaking so jenkins listens for both topics, and runs the same thing on both.

**Comment by tdawson** [comment]
I believe this ticket is done.  I have not heard anything back from the OpenQE people I contacted.  But their code was quite straightforward.

**Comment by tdawson** [comment]
Heard back from OpenQA (Adam Williamson).
It looks like everything is in place for OpenQA to re-run tests.

> The consumer schedules *all the relevant tests* when it gets a 'bodhi update created or
edited' message (note that 'edit the update and add an extra space or something to the description' is a hack you can use *right now* to force openQA to re-run all the tests on an update).

But, that will re-run *all* the tests.  That may, or may not be, a waste of resourced.  If you just want one test to be run ...

> openQA does literally have the concept of 're-run this
specific job' (by ID). So for openQA this isn't a difficult problem:
fundamentally all we need to do is pass the message 'hay openQA re-run
job XXXXXX' along the line, whether that's by giving the re-run
mechanism direct openQA API access, or having it publish a fedmsg /
fedora-message which we have the openQA scheduler pick up.

**Comment by thrix** [comment]
As for Fedora CI pipeline, we should ideally define new messages for restarting testing, not reuse the existing messages, but the former is definitely easier to do now. The thing is, there might be some other systems reacting on those messages, and we really want just to be a restart on the CI pipelines / testing systems, not also on other systems ....

**Comment by AdamWill** [comment]
Yes. Re-sending the messages would be really bad. Please don't do that. The messages are supposed to be a source of truth, they aren't just conveniences for triggering tests. A `org.fedoraproject.prod.buildsys.build.state.change` message is supposed to mean a build state change really did occur in the production build system, it is not supposed to mean "nothing actually happened to this build but we are abusing the messaging system to re-run some tests".

It is not difficult to just update the CI consumer to listen out for a few more topics, please do that instead.

**Comment by tdawson** [comment]
Those are very good points.  Thank you.

Whoever is doing the code to re-run the tests, should not take the shortcut of re-broadcasting the buildsys.build.state.change message, for any of the testing platforms.  Doing so can affect much more than just the testing.

**Comment by cverna** [comment]
We need to coordinate that with the CI team and start agreeing on what the re-trigger test message will look like

**Comment by thrix** [comment]
I will be happy to define the messages in https://pagure.io/fedora-ci/messages ... will do it today .. and ask you all for review ...

Related issue: https://pagure.io/fedora-ci/messages/issue/3

**Comment by cverna** [comment]
@thrix did you get a chance to look at this ? Once we have the message format we can start to look at adding the possibility to send this message from bodhi.

**Comment by cverna** [comment]
Lets close this since we now have a way to do that via https://github.com/fedora-infra/bodhi/issues/3428

**Comment by AdamWill** [comment]
How does that solve this? AFAICS #3428 implements an automatic mechanism for Bodhi to publish a message when it decides an update is "ready for testing". I don't see that it provides a mechanism for packagers to manually trigger the publishing of such a message in order to have the tests re-run.

**Comment by cverna** [comment]
The same way we publish a message to say the update is ready for testing, we can publish a message to request the tests to be run again.That's why I closed this ticket, I don't think we need to investigate how we will do that anymore.

Implementation will most likely be done in https://github.com/fedora-infra/bodhi/issues/3287 and https://github.com/fedora-infra/bodhi/issues/3288

**Comment by thrix** [comment]
@cverna Yeah, sorry, not yet, anyway, basically request for test message could be also standardized. It is not much different by the retrigger messages really ....

**Comment by AdamWill** [comment]
I mean, I think @cverna might be right - it doesn't need to be a different message, just use *this exact* message. As a test system maintainer, it works fine - I just make my test system fire the tests any time I see this message. It doesn't matter to me whether Bodhi is publishing it because an update just got created or because the maintainer pushed a "re-run these garbage tests" button.

Though I suppose if we want to do anything more fine grained than "re-run absolutely every test on this update", we'd need something different...

**Comment by thrix** [comment]
@AdamWill  Ok, maybe we are speaking about different use cases. Fedora CI reacts on koji builds, so you want to send out a ```org.fedoraproject.prod.buildsys.build.state.change``` messages?

[1] https://github.com/CentOS-PaaS-SIG/upstream-fedora-pipeline/blob/master/JenkinsfileBuildTrigger#L31

**Comment by AdamWill** [comment]
I guess this ticket was scoped to Bodhi, so if you think about the problem in the scope of Bodhi, just re-sending a 'ready for testing' message makes sense.

I think we kicked around the idea of having a whole convention/framework/something for "test retrigger requests" that Bodhi could use and Koji could use and anything else could use before, but it didn't really get anywhere in the end. It seems like quite a lot of engineering, I think. I mean, there's also the UI to think about: right now there's barely any point to log into Koji at all, for instance, so I don't know if there's even a UI for *that*, before we even get into where the "re-run tests for this build" button would go...
