### ISSUE TITLE
Bodhi lies about the number of proventesters that are required if there's a release override

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2351]
Today a [releng ticket was filed](https://pagure.io/releng/issue/7482) in which Bodhi [posted a confusing comment](https://bodhi.fedoraproject.org/updates/FEDORA-2018-fc3904edc1) on an update that said that 0 proventester karma points were required, when in fact 1 was required due to the F28 release having defined ```f28.post_beta.critpath.num_admin_approvals = 1```. The [code](https://github.com/fedora-infra/bodhi/blob/3.6.1/bodhi/server/models.py#L2514-L2522) only considers the ```critpath.num_admin_approvals``` setting to write that comment, even though the ```f28.post_beta.critpath.num_admin_approvals``` setting can override it.

We can fix this two ways: we could correct this comment to match up with reality, or we could possibly drop the proventester feature since it doesn't seem to be used in Fedora's deployment and does add complication to Bodhi's state machine. Doing the latter would be a backwards-incompatible change and should probably also get buy in from releng and QA.

**Comment by AdamWill** [comment]
The proven tester concept is currently 'on hiatus', per https://fedoraproject.org/wiki/Proven_tester , and has been since 2013. No-one seems particularly passionate about bringing it back, at least not right now. Given that, I think it'd be fine to remove it from Bodhi if it makes things cleaner. I guess we could always wire it back in later on if necessary.

**Comment by keszybz** [comment]
After 2 years, it seems even more unlikely that proventesters will come back...

**Comment by cverna** [comment]
Lets close then
