### ISSUE TITLE
The update system has the wrong package

### ISSUE THREAD

**Issue by stevedd** [fedora-infra/bodhi#2397]
I'm trying to update the rpcsvc-proto package. 

When I try to create a new update, the system
only gives me rpcsvc-proto-devel as a choice
not rpcsvc-proto.

This is clearly a bug since rpcsvc-proto-devel
is part of rpcsvc-proto

**Comment by puiterwijk** [comment]
This is actually a bug in Fedora Packages, since that's where the search comes from: https://apps.fedoraproject.org/packages/s/rpcsvc-proto.
Please file this on https://github.com/fedora-infra/fedora-packages/issues/new .

Do note that you can also ignore the search function and just manually import NVRs and bugzilla IDs.

**Comment by bowlofeggs** [comment]
This bug is likely what you are hitting: https://github.com/fedora-infra/fedora-packages/issues/229
