### ISSUE TITLE
ypserv update history is missing

### ISSUE THREAD

**Issue by mmuzila** [fedora-infra/bodhi#2441]
Update history of ypserv is missing in bodhi. There definitely were updates in past (the last one cca a year ago, ypserv-4.0-2.20170331git5bfba76.fc27). As you can see[1] no update history is shown, except the todays update.

Until I created an update[2] today, I was unable even to find ypserv in bodhi.

[1] https://bodhi.fedoraproject.org/updates/?active_releases=true&search=ypserv
[2] https://bodhi.fedoraproject.org/updates/FEDORA-2018-1fbfbc34fc

**Comment by bowlofeggs** [comment]
Are you sure there were ypserv Bodhi updates in the past? I spot checked builds done over the past two years, and none of them were tagged into updates-testing:

https://koji.fedoraproject.org/koji/packageinfo?packageID=259

They all look like they were tagged into the base repository, which Bodhi does not manage. I think you might possibly actually be the first person to ever update ypserv in a Fedora release ☺

**Comment by mmuzila** [comment]
Yes, I am sure. There is a build[1] that was submitted[2] as an update.

[1] https://koji.fedoraproject.org/koji/buildinfo?buildID=519274
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1100354#c2

Matej

**Comment by bowlofeggs** [comment]
Interesting. I have no idea how to explain that, other than it might be that that was Bodhi 0.9 instead of Bodhi 2 that long ago. I wasn't around on the project at that time, so am not familiar with the history. I am not sure if this indicates a bug in the current version of Bodhi, or at least I've not seen other similar reports.

**Comment by mattiaverga** [comment]
You should query without `?active_releases=true` otherwise Bodhi only shows you updates under currently active releases (F27 and newer, EL6, EL7).
So you should search with:
https://bodhi.fedoraproject.org/updates/?search=ypserv

BUT I think updates history starts with F21 because, for example, searching for `kernel` or `xorg-x11-server` updates stops there:
https://bodhi.fedoraproject.org/updates/?search=kernel&page=26
https://bodhi.fedoraproject.org/updates/?search=xorg-x11-server&page=4

**Comment by bowlofeggs** [comment]
Ah yes, @mattiaverga makes a good point about removing that filter. I think we can close this issue.
