### ISSUE TITLE
Request for feature: It would be cool to be able to filter updates by type of update (bug, improvement, security...)

### ISSUE THREAD

**Issue by heis2201** [fedora-infra/bodhi#2619]
It would be cool to be able to filter updates by type of update (bug, improvement, security...)

**Comment by bowlofeggs** [comment]
@heis2201 This is possible - if you visit https://bodhi.fedoraproject.org/ you can click on all the little icons in each release and they will filter that release and stage for bugs, enhancements, newpackages, and security updates. You can also hand edit the URLs they produce to form your own queries. The CLI is a little more powerful for searching than the web UI is here (since the web UI doesn't have a query building UI of its own) and lets you do those things without hand editing the URL.

Here's an example for stable Fedora 28 security updates:

https://bodhi.fedoraproject.org/updates/?releases=F28&status=stable&type=security

You can just cut that F28 out if you want all stable security updates, for example:

https://bodhi.fedoraproject.org/updates/?status=stable&type=security

**Comment by heis2201** [comment]
Thanks for your quick reply.

adding ```&type=security``` does the trick.
