### ISSUE TITLE
stable_karma and unstable_karma values in API data should not be allowed to be 'None'

### ISSUE THREAD

**Issue by tflink** [fedora-infra/bodhi#274]
At the time I'm writing this, there are updates whose API data includes 'None' for the `stable_karma` and `unstable_karma` values. The example I hit is [bash-4.3.42-1.fc21](https://bodhi.fedoraproject.org/updates/FEDORA-2015-13654) but at least the updates for bash in other releases show the same issue in api data.

The updates submitted after the bodhi2 upgrade seem to have `stable_karma` (the updates for [the latest gnome megaupdate](https://bodhi.fedoraproject.org/updates/FEDORA-2015-13858) and [python-django](https://bodhi.fedoraproject.org/updates/python-django-1.8.4-1.fc22) amongst others do) where the updates that were submitted before the upgrade and migrated over to the new bodhi2 instance don't.

`stable_karma` is an important piece of data which should always be an integer. If the old updates are left as is (assuming I'm right about old updates not have `stable_karma`) they should at least return 0, a sane default (assuming that `None` means that nothing was changed from the default of 3) or some obvious filler data (-9999999).

**Comment by ralphbean** [comment]
Looking back over the code, it seems like it is intentional to allow ``None`` values for karma thresholds.

* The database models marks them as explicitly nullable.
* The new update form allows you to check a box to disable "Auto-request stable"
* When checked, that flag causes the server to *delete* the submitted values for stable and unstable threshold.

So, for some updates -- those thresholds are meaningless, and it makes sense to return a ``None`` value indicating as much.

Aside from that, it does look like a migration error caused the old karma thresholds to be dropped from all the migrated updates.... and that's worth fixing up(?)

**Comment by tflink** [comment]
So `None` for `stable_karma` means that auto-request has been disabled for that update?

**Comment by ralphbean** [comment]
I'll hazard a "yes".  That's the only circumstance I've found in the code where it gets set that way.

**Comment by sergiomb2** [comment]
Hi, stable_karma and unstable_karma simple disappear from all updates, I pretty sure because my updates don't have it now , and all had it .  Also stable_karma is not working  , 

https://bodhi.fedoraproject.org/updates/FEDORA-2015-4638  

I think that had 3 for stable_karma, I added +1 karma yesterday , but bodhi2 haven't push it .

**Comment by ralphbean** [comment]
@sergiomb2, that's a separate migration issue (that is in fact an issue).  You can follow the status of that in #372.

As for this issue, Luke and I agree that having ``None`` for stable_karma means that auto-request has been disabled for that update.

**Comment by tflink** [comment]
Thanks for the clarification
