### ISSUE TITLE
bodhi.server.services.updates.new_update() has an assert statement

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#2848]
There is an [```assert``` statement](https://github.com/fedora-infra/bodhi/blob/3.11.3/bodhi/server/services/updates.py#L507) in ```bodhi.server.services.updates.new_update()```. This assert looks like it might be important for correct operation, but the problem is that assert statements get stripped out of optimized Python builds (so the statement won't be present in production).

**Comment by sebwoj** [comment]
After some investigation, I think that it is impossible to reach this line because of:
https://github.com/fedora-infra/bodhi/blob/d1600a16e9bdeeaed9d454f9668010ab8c179511/bodhi/server/validators.py#L306

Related UT:
https://github.com/fedora-infra/bodhi/blob/d1600a16e9bdeeaed9d454f9668010ab8c179511/bodhi/tests/server/services/test_updates.py#L2970

To substitute "assert statement", we can raise BodhiException(with the assert statment  info) in the same place(and add "catch" snippet couple lines after), but without unittest.
@bowlofeggs What do you think?

**Comment by bowlofeggs** [comment]
@sebwoj yeah that seems solid to me. I think we can just drop the ```assert``` statement.

**Comment by bowlofeggs** [comment]
A fix for this issue is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/
