### ISSUE TITLE
Enhancement request: Markdown cheatsheet

### ISSUE THREAD

**Issue by cicku** [fedora-infra/bodhi#286]
It's better to include a `Markdown supported` link like Github on the right of the `Update notes` box.

**Comment by ralphbean** [comment]
Good idea.  We may just link to the [daring fireball notes](http://daringfireball.net/projects/markdown/) directly instead of embedding our own cheatsheet (even though we have some [special rules](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/ffmarkdown.py#L35-L75) like linking to BZ tickets, etc..)

**Comment by cicku** [comment]
It'd be better to include Fedora-specific markdown grammars if you'd like to. :clap:
