### ISSUE TITLE
Bodhi should block pushing kernel updates where user karma feedback has indicated that it renders the system unusable

### ISSUE THREAD

**Issue by edwintorok** [fedora-infra/bodhi#2874]
4.19.9-300.fc29.x86_64 is unusable (missing firmware resulting in black screen).
There was user karma feedback saying it doesn't work at all, with negative karma on both questions, and a linked bugreport:
https://bodhi.fedoraproject.org/updates/FEDORA-2018-2645eb8dab#comment-875465

Yet later the update got pushed to stable:
https://bodhi.fedoraproject.org/updates/FEDORA-2018-2645eb8dab#comment-875607

I think Bodhi should be more strict about kernel pushes.

**Comment by bowlofeggs** [comment]
The maintainer decided to push that update to stable. I don't believe Bodhi should override maintainer decisions. It takes human judgement to weigh the risks of pushing vs. holding an update. Consider that this was a security update and the decision may not always be very easy. Should you hold a security update from some users because it doesn't work for others? A computer is not good at making these decisions, and that is why Fedora has package maintainers. Bodhi's job is just to provide a platform for testers and maintainers to interact so that the maintainer has information to base their decision on, and I think Bodhi did its job here.

**Comment by edwintorok** [comment]
Would be good to avoid mixing security updates with updates that change firmware requirements, but that is probably not something bodhi can check, it would be up to the maintainer, I agree.
Having some automated tool to check it might be good though (like taskotron?), but it is probably not obivous how to check from the binary what firmware it requires (initramfs builders sometimes complain about possibly missing firmware, perhasp the output from that could be diffed between updates of kernel packages to help the maintainer catch bugs like this early?)

**Comment by bowlofeggs** [comment]
@edwintorok that might be hard to avoid, since Fedora tracks the upstream kernel as closely as is feasible. Upstream often mixes many changes together in any given update. I honestly think the kernel packagers have to make a lot of tough decisions when it comes to updates.

We do have automated testing in Fedora, but the kernel is especially difficult to automatically test because we don't have all the various hardware that people use Fedora on in our set of testing systems.

**Comment by edwintorok** [comment]
I don't disagree, hence I was looking for source or binary level tests that do not require access to hardware, and could be done at build (or push) time.
I think this is the problematic commit: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.19.y&id=39bdb32876df3710825d33b5c455ec2ffa9db64e
Perhaps just diffing the two kernel versions, and grepping for MODULE_FIRMWARE changes would be a good first step, then the maintainer can look at the affected commit and decide whether to revert just those commits when pushing a security patch (unless the firmware *is* the security patch).
Perhaps such a tool should be part of upstream kernel, and automatically included in release announcements such as https://lwn.net/Articles/774847/ (e.g.
`Notice to distro maintainers: this update requires new firmware due to commits X,Y,Z. Please ensure that you push updated firmware packages together with your kernel packages, or revert these commits`
