### ISSUE TITLE
Deliverables should have their own types and icons

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/bodhi#2941]
I've just discovered that Bodhi hosts [different types of artifacts](https://github.com/fedora-infra/bodhi/issues/2261#issuecomment-455163920).

* packages
* modules
* containers
* flatpaks

This could be more obvious if they had personal mnemonics or/and at distinct color. 

Then they could be grouped into big parent "Fedora 29" div on the front page. Right now they are not grouped.

![image](https://user-images.githubusercontent.com/8781107/51323619-c0d41400-1a79-11e9-8370-fc14f5a122eb.png)

**Comment by bowlofeggs** [comment]
Yeah they are not grouped because in Bodhi's modeling they are considered to be entirely separate releases. So even though they all start with "Fedora 29", Bodhi does not consider them to be related in any way.

If we wanted to make them have a relationship, I suppose we could great a ReleaseGroup object or something along those lines. I'm not sure what features this would enable though. What use cases do you have in mind?

**Comment by abitrolly** [comment]
The primary case is that making information more readable will make more users willing to discover the differences between different choices available for their OS version, leading into better conversion to developers in the long term.

**Comment by ryanlerch** [comment]
IMHO, this one is not really an issue anymore, with the new frontpage, and releases page in Bodhi 5.
