### ISSUE TITLE
Unable to override a build

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/bodhi#295]
Hi,

with bodhi 1.0 I was able to override a build. With bodhi 2.0 I can not. Is this intended or a bug?

I am getting:
$ bodhi --buildroot-override=golang-github-coreos-go-systemd-3-1.fc23 for f23-candidate --duration=20 --notes='temp non-stable dependecy waiting for stable'
Traceback (most recent call last):
  File "/usr/bin/bodhi", line 537, in <module>
    main()
  File "/usr/bin/bodhi", line 433, in main
    }, auth=True)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 355, in send_request
    output = func(method, auth_params, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 84, in _decorator
    output = func(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 301, in _authed_post
    response = self._session.post(url, params=params, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 377, in post
    return self.request('POST', url, data=data, **kwargs)
TypeError: request() got an unexpected keyword argument 'req_params'

$ rpm -q bodhi-client
bodhi-client-0.9.12.2-3.fc21.noarch
$ rpm -q python-fedora
python-fedora-0.5.5-1.fc21.noarch

Thanks
Jan

**Comment by lmacken** [comment]
Yep, we need to push the new bodhi2 cli out to fix this.

**Comment by bowlofeggs** [comment]
bodhi-2.2.4 is now in Rawhide, and there's an EL 7 update with it as well at https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-3081a94111

We can't release bodhi 2 to Fedora 23, 24 or 25 since it is backwards incompatible. However, the Bodhi 2 CLI is available in my Copr for those Fedora releases: https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi/

I'm going to close this bug since it's not an issue in upstream code, and since the Copr is available for all supported downstream releases of Fedora (and soon bodhi 2 will be in supported releases, started with Fedora 26). Thanks for the report!
