### ISSUE TITLE
[M] Give Bodhi a feature flag to be able to make test gating decisions/waivers using ResultsDB directly

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/bodhi#3053]
We should give Bodhi a configuration setting that toggles which source it uses for test gating decisions. If the setting is set to "greenwave", it would do what it does today. If it is set to "bodhi", then Bodhi would not consult Greenwave or WaiverDB, and would instead use its existing test gating code to make gating decisions.

We do need to add or adjust some features for the "bodhi" value to work:

* Releases need to have a list of required tests that all updates related to the release need to pass.
* We need to be able to consume the gating.yaml file that Greenwave uses. It may be possible to import Greenwave to do this, but it is likely simple enough to do on our own.
* We need a Waiver model and an API to create waivers.
* The existing gating decision code needs to be updated to consider the waivers, the release policy, and the gating.yaml file.

I did a prototype for some of this in August that included the release policy and it was straightforward. It took me about 30 minutes and ended up being fewer than 10 lines of code since Bodhi already has the code to pull tests from ResultsDB.

**Comment by cverna** [comment]
So I think we might want to prioritize #3204 over this work, since #3204 is backward incompatible and we likely want to have this ready with #2851 to do a 5.0 release.

**Comment by abompard** [comment]
(sorry I pressed the wrong button)

**Comment by AdamWill** [comment]
does anyone still want to do this?

In theory I agree that all the indirection via greenwave isn't really *necessary* as bodhi turns out to be really the only consumer of it (we've more or less given up on gating composes at this point), but we more or less understand how it works and we've done quite a lot of work on it lately to make things more correct and make the webUI output more useful. There's at least me and @hluk who mostly understand how stuff works.

if nobody has a burning desire to do this any more, maybe we could close the ticket?

**Comment by mattiaverga** [comment]
Agreed from my POV, please reopen if anyone has any objections.
