### ISSUE TITLE
rpmlint check - changelog-time-in-future

### ISSUE THREAD

**Issue by FrostyX** [fedora-infra/bodhi#311]
I've submitted this update <https://bodhi.fedoraproject.org/updates/tracer-0.6.5-1.fc21> in which rpmlint failed on:

    tracer.noarch: E: changelog-time-in-future 2015-08-22
    tracer.src: E: changelog-time-in-future 2015-08-22

It is strange, because submitted time is: 2015-08-22 00:31:46.088108

**Comment by ralphbean** [comment]
Thanks for reporting!  That issue would actually be [better filed with taskotron](https://phab.qadevel.cloud.fedoraproject.org/maniphest/task/create/), since that's the system that is running those checks.  Bodhi's UI is just displaying them.  If you re-file this issue over there, one of the QA devel crew can probably help out.
