### ISSUE TITLE
Automatic updates should be filled with information from the RPM changelog

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/bodhi#3192]
This is a continuation of issue #3007 and covers items deemed not that high of a priority, not needed for the MVP.

As a Bodhi user, when an update is created automatically because a build was tagged into a certain tag, I want that new entries in the changelog are evaluated and:

- discovered Bugzilla tickets are associated with the update
- changelog entries are used to pre-fill the update notes

so that the update is more informational.

Thoughts:

- We need to figure out what the new changelog entries are. Between builds, we could e.g. have more than one entry. Old entries could even be removed, or existing metadata changed (e.g. when a previously wrong changelog date or weekday is fixed) which makes discovery of "what is new" harder.
- When a new build triggers a new update, it should probably obsolete and already existing (but active) update of the same package, and inherit Bugzilla tickets and update notes. With manually created updates, the notes could just be merged and the maintainer would sort out commonalities etc. How would we handle this automatically?

**Comment by keszybz** [comment]
This applies to "manual" updates too. It'd be great if bodhi could pre-fill the bug description with bug numbers and the text from the changelog. Right now bodhi suggests no text and for bugs it just picks a few bugs from the list of open bugs, which means that for packages with many bugs open the suggestion is essentially useless. The text would often have to be edited (because the level of detail in the changelog is different), but it'd be a good start and make things quicker in many cases.

**Comment by bowlofeggs** [comment]
@ryanlerch Are you still planning to work on this? If not, I might take a swing at it.

I think we can break this code out into its own function to get the changelog for us here (and to continue to do so for the e-mails):

https://github.com/fedora-infra/bodhi/blob/41412fffd5b981f5a61d4ece7f43b54f3390f36e/bodhi/server/mail.py#L342-L354

**Comment by keszybz** [comment]
Wow, thanks!
