### ISSUE TITLE
"Locked: This update is currently locked and cannot be modified. "

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/bodhi#323]
I'm trying to add a build to an update. But I see $subject. This is missing information by whom, for what reason, and for how long, and whether I can override that.

https://bodhi.fedoraproject.org/updates/rpm-mpi-hooks-3-2.fc23,mathgl-2.3-10.fc23,elpa-2015.05.001-2.fc23,freefem++-3.31-7.3.fc23,netcdf-4.3.3.1-5.fc23,MUMPS-5.0.1-2.fc23,gpaw-0.11.0.13004-15.fc23,ga-5.3b-18.fc23,valgrind-3.10.1-19.fc23,boost-1.58.0-6.fc23,dl_poly-1.9.20140324-14.fc23,hpl-2.1-13.fc23,netgen-mesher-5.3.1-8.fc23,espresso-3.3.0-7.fc23,scotch-6.0.4-5.fc23,hdf5-1.8.15-6.patch1.fc23,scalapack-2.0.2-10.fc23,gromacs-5.0.6-6.fc23,scorep-1.4.2-2.fc23,sundials-2.6.2-4.fc23,Ray-2.3.1-11.fc23,orsa-0.7.0-33.fc23,elk-3.1.12-14.fc23,mpich-3.1.4-5.fc23,openmpi-1.8.8-3.fc23,mpi4py-1.3.1-14.fc23,pypar-2.1.5_108-11.fc23,paraview-4.3.1-11.fc23

![update-locked](https://cloud.githubusercontent.com/assets/349618/9424474/eeb74722-48bb-11e5-8a4c-93dd8dde339a.png)

**Comment by ralphbean** [comment]
So, FYI this is because your update got included as part of a mash.  At the beginning of the mash, the bodhi2 masher now locks all the updates so they can't be modified in the middle of that.  This was the source of *endless* rel-eng woes with bodhi1.

This needs to be documented in the webapp, like you say.

**Comment by ralphbean** [comment]
Fixed in 05e5dda15a28fa494af4b718a2c41a00935e978c
