### ISSUE TITLE
Koji fedmsgs are different in stg and prod

### ISSUE THREAD

**Issue by abompard** [fedora-infra/bodhi#3304]
According to the [Fedora Messaging progress board](https://github.com/orgs/fedora-infra/projects/2), Koji's Fedora Messaging port is in staging but not in prod. The way the AMQP-ZMQ bridges work is that fedmsg messages are published to AMQP without change, thus with the message content in a `msg` key [this has been reported](https://github.com/fedora-infra/fedmsg-migration-tools/issues/20). As a result, in staging bodhi got messages from the AMQP version of Koji, but will receive in prod messages that may look different (message content in the `msg` key). We have recently adapted to the messages we saw in staging with commit 884a0ccd. It's possible that until the bridges are fixed to squash the `msg` key, the prod version of Bodhi crashes on Koji messages.
Looking at the Bodhi logs I don't see those crashes, but I also don't see any incoming messages on the `buildsys.tag` topic being logged. I checked the subscriptions and they are OK. How can I check that the signed handler is actually doing its job?

**Comment by bowlofeggs** [comment]
Hey @abompard - I have been noticing that the signed handler is not doing it's job in production: https://pagure.io/fedora-infrastructure/issue/7877

This seems like a likely explanation of why that is happening.

The good news is that it's OK if the signed handler doesn't work because bodhi-push will poll to find out if unsigned builds have been signed, so things are actually still working OK due to that.

IMO, we can probably just wait for production Koji to send the new messages and take no action on our part. What do you think?

**Comment by abompard** [comment]
Actually the bridges are likely to be fixed sooner than that. So yeah we don't have to do anything, except close the infra issue as your already did.

**Comment by abompard** [comment]
FYI the bridges have been updated in prod and the signed handler should start working.
