### ISSUE TITLE
check_policies script seems to be unused

### ISSUE THREAD

**Issue by sebwoj** [fedora-infra/bodhi#3387]
Since we have a GW msg consumer, we can remove this script in the next big release.

**Comment by pypingou** [comment]
IIRC, the idea was to have a belt+suspender approach where we would do bus-based notifications by default and use the cron to clean things up if needed.
Since we moved from fedmsg to fedora-messaging this may not longer be required, so :+1: for dropping it, although I'd encourage that we give our new consumer enough time to be sure that it behaves as we want :)

**Comment by richardgreg** [comment]
@cverna can I do this?

**Comment by karmadolkar** [comment]
@cverna are we only deleting a file in this issue?

**Comment by cverna** [comment]
Ok so after talking with @pypingou on IRC, I think we might want to keep this is place. This script is currently running as a cronjob (https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/bodhi2/backend/tasks/main.yml#n193).

This is still useful because sometimes Greenwave fails to reply to Bodhi's requests and the cron job will provide a second chance to get the response from Greenwave.

So I think I am more on the side of just closing that ticket and keep that script.

Any other opinions ?

**Comment by pypingou** [comment]
> So I think I am more on the side of just closing that ticket and keep that script.

+1 for me

Somehow, I'm not saying one thing and its opposite in a single ticket :(
Maybe we could somehow gather some stats of how often has the cron job saved us and use this data to make a decision?

**Comment by cverna** [comment]
Closing since this is not an issue
