### ISSUE TITLE
Have bodhi send a dedicated fedora-messaging message when an update is ready to be tested

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/bodhi#3428]
Updates are manually created in a "Pending" state, where they are signed before they are pushed to a "Testing" where they are tested by the CI system.
So we can't trigger the CI system off new updates being created.

The easiest solution is thus to send a dedicated fedora-messaging message to tell the CI System: "Now this update can be tested".

This need coordination with the OSCI team maintaining the CI system.

**Comment by abompard** [comment]
Could you explain a bit more what is needed and what the problem currently is?
If I understand correctly, CI reacts on Koji builds, and that won't work for multi-package updates because we need to test them all together. So we can solve that problem by sending a (new) message when an update is ready to be tested.

I'm guessing we want to send that message when the update / update set lands in the testing repository? Thus after a compose?

What kind of information do we want in that message?

**Comment by pypingou** [comment]
>    Could you explain a bit more what is needed and what the problem currently
>    is?
>    If I understand correctly, CI reacts on Koji builds, and that won't work
>    for multi-package updates because we need to test them all together. So we
>    can solve that problem by sending a (new) message when an update is ready
>    to be tested.

So far so good :)

>    I'm guessing we want to send that message when the update / update set
>    lands in the testing repository? Thus after a compose?

Rawhide has no testing repository so that won't work then :)

For stable releases, we gate going to testing and going to stable, so we likely
will send the message when the update is submitted to testing and when it's
submitted to stable.

>    What kind of information do we want in that message?

This is *the* question which we're still trying to figure out :)
