### ISSUE TITLE
Missing dnf instructions for updates-testing

### ISSUE THREAD

**Issue by Yky** [fedora-infra/bodhi#3455]
In the past, bodhi displayed dnf instructions for installing packages from updates-testing. 

For example, there used to be instructions with a yellow background for the following package:
https://bodhi.fedoraproject.org/updates/FEDORA-2019-c8703a3fb3

`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2019-c8703a3fb3`

This command is no longer shown for kernel-updates (and possibly other updates for testing). I've noticed this for roughly a month.

**Comment by mattiaverga** [comment]
This is because after the update to 4.1.0 the existing releases (at least those which are active) should have been manually edited by an administrator to add `package_manager` and `testing_repository` properties. Without those two properties set, no command is displayed.

See the release notes https://github.com/fedora-infra/bodhi/blob/develop/docs/user/release_notes.rst#features

**Comment by Yky** [comment]
Thank your for your quick response. 

Is there a specific reason why no default is provided to display the install command for an update? I could imagine a lot of maintainers did not take note of this change. New updates added after the bodhi update do not contain the install command either.

**Comment by mattiaverga** [comment]
It was decided to not add defaults because it's impossible to predict any. We made the change not only focusing for our instance of Bodhi (Fedora and Fedora EPEL), but there are also other instances used by other distro that we cannot predict what package manager are using or how they name their testing repositories.

**Comment by cverna** [comment]
@abompard could you set the `package_manager` and `testing_repository` in our ansible repo and redeploy so that we can close this issue ?

**Comment by mattiaverga** [comment]
Can someone step up and fix this?
Also, new Fedora releases should be set up with `package_manager=dnf` and `testing_repository=updates-testing`, but F32 wasn't.

**Comment by pypingou** [comment]
I've updated the DB for Fedora's releases to support this and opened https://github.com/fedora-infra/bodhi/issues/3541 to allow doing this without messing with the DB itself.
