### ISSUE TITLE
bodhi client requires display_name field during update

### ISSUE THREAD

**Issue by onosek** [fedora-infra/bodhi#3470]
Hi,

I am maintaining fedpkg. Recently it started failing because of new bodhi client bug/feature that allows the user to customize the name of the update (display_name). It happened in bodhi-4.1.0-3 which build is available (only) for Fedora31. I temporarily fixed it for Fedora31, but as this bodhi change is not backwards compatible, it is complicated to resolve it for other releases. I would have to test which bodhi version is available and upon this test result, I would need to customize communication with bodhi client. And for every release require a different version of bodhi.
Bodhi web interface AFAIK doesn't require any input in this field. Why bodhi client interface requires it? Isn't it possible to change this behaviour from mandatory to optional?
Thank you.

You can see more information here:
- https://bugzilla.redhat.com/show_bug.cgi?id=1737426 
- https://pagure.io/fedpkg/issue/349
- https://github.com/fedora-infra/bodhi/blob/develop/bodhi/client/bindings.py

**Comment by ryanlerch** [comment]
It looks like that the issue here is that fedpkg is not supplying the display_name item in the update config file it is passing to the bodhi CLI.

the Bugs field is not mandatory either, but the config file that fedpkg supplies to bodhi (if there are no bugs), contains the field, but is empty. Pretty sure that changing the config template in fedpkg to contain the field, but defining it as empty will fix this issue.

**Comment by lubomir** [comment]
It does fix the issue if you have bodhi client 4.1.0. If `display_name` is included in the template for 4.0.2, bodhi will complain and crash. Basically fedpkg would have to do runtime detection of minor bodhi version. It seems much easier to provide default empty value in bodhi directly. Otherwise I think a major version bump is in order, since it breaks backwards compatibility.

**Comment by onosek** [comment]
Hi @ryanlerch, I would like to ask about the situation. Is there any plan for fixing this? If yes, what is your time estimation? Thank you.

**Comment by onosek** [comment]
Closing this issue as a requested change was merged. Going to be released soon in bodhi 5.
