### ISSUE TITLE
Call to get candidates in new update form is now slow

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#3687]
Previously, the ajax call we used to populate the builds chooser in the new update form took a couple seconds to load. However, since the introduction of this fix:

https://github.com/fedora-infra/bodhi/pull/3670

this call now takes upwards of 30seconds on stg. (not sure if this will be quicker on prod, but it is pretty slow atm.) the endpoint is : https://bodhi.stg.fedoraproject.org/latest_candidates?hide_existing=true&prefix=

not sure what is taking so long here, it doenst look like there are any additional calls to koji that is slowing it down...

**Comment by nphilipp** [comment]
I've looked into this and it's because it queries the database for each build it gets from koji which can be on the order of thousands if the prefix is empty.

Here's my idea how to optimize this: rather than querying for each build in the database, query the database once for NVRs of builds of an active release, with an associated update, then check if a particular build NVR is in this set.

**Comment by nphilipp** [comment]
Testing this in my local Vagrant box (set up to query koji.stg), I got this down to 3~5 seconds for an empty prefix. I'll submit a PR with it.
