### ISSUE TITLE
Bodhi 5.0: new way to add build is terrible

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#3707]
Please, switch back to previous way

Being able to simply add build is important.

Current version is slow, and don't work well when trying to paste package name in input.

Old way is also better because allow to copy/paste NEVR during the build, without anything tagged yet.

**Comment by mattiaverga** [comment]
I strongly disagree, I think @ryanlerch made a great work.

Maybe it would be more straightforward for whose coming from the old UI to have the "Builds" tab as first element in the form, over the "Metadata" tab.

In my opinion, disallowing to copy/paste custom text in the Builds field prevents to enter wrong data, so it's good. If one has to enter many NVRs, they can now search in the same field for their user name, so they'll see all updates-candidate associated with the username. (maybe this option should be more explicit in the placeholder).

**Comment by kalev** [comment]
I second to that. We need a way to quickly copy-paste 100+ build IDs for creating GNOME mega-updates. Previously it was just the matter of preparing a space-separated list and copy-pasting it into the build IDs section; now it no longer appears to work.

**Comment by mattiaverga** [comment]
@kalev you can now do that by preparing the mega-update in a side tag and then using that side tag in the Builds field ;-)

**Comment by cverna** [comment]
> @kalev you can now do that by preparing the mega-update in a side tag and then using that side tag in the Builds field ;-)

Only for rawhide tho :-), the sidetag will not be available to all releases in a first step.

**Comment by remicollet** [comment]
> they can now search in the same field for their user name

Not user friendly, list is too long. Not even sorted

**Comment by kalev** [comment]
> > they can now search in the same field for their user name
> 
> Not user friendly, list is too long. Not even sorted

And also, we don't have a single person doing all GNOME builds. I really need a way to copy-paste a list of builds here for the UI to be usable for GNOME mega-updates.

**Comment by pghmcfc** [comment]
I too like to be able to prepare updates in the GUI whilst the build is going. Not only can't I paste in the build, I don't seem to be able to add bug numbers either.

**Comment by ryanlerch** [comment]
> I second to that. We need a way to quickly copy-paste 100+ build IDs for creating GNOME mega-updates. Previously it was just the matter of preparing a space-separated list and copy-pasting it into the build IDs section; now it no longer appears to work.

This still works now, except where as before you could have comma or space separated lists, now it is comma separated lists only. This is because this element also has the ability to search all the candidate builds, so you can type "kalev gnome fc31" and it will filter on all those items.

**Comment by ryanlerch** [comment]
Trying to get down to the crux of the pain here, and it is the fact that  you are Unable to add a build that is not actually built yet, is that correct?

Here is a breif screencast of the ability to paste a big list of updates (comma separated), and the ability to serarch on username, and others:


![screencast](https://user-images.githubusercontent.com/592259/68821222-72af9180-06d9-11ea-868b-fb3ed5d50fdf.gif)

**Comment by ryanlerch** [comment]
Okay, trying to read a bit past the initial **it's 'orrible** comments to try to figure out what is causing the pain here, and it seems there are two pain points. If there are any others, please help us out by **clearly describing what issues you have**. 

The previous new update form was _very_ confusing for new users, and this updated version's goals were to make it easier for the majority of users to search and find the candidate build to add, as well as make it easier for integrating the sidetag functionality. 

Here are the two valid points i could extract from the thread so far:
 
### 1. Adding builds that don't exist (yet)
Previously, it was possible to arbitrarily add a build to the list in  the UI that was not tagged as a candidate build. Of course if the form was submitted without this build being tagged (i.e. it is currently in the process of being built), the update would not be created. 

Note too, that no client side validation of any kind was done when adding a build here, so you could add "foopants" and it would be added to the list.

The new builds adder now only lets the user add builds that are tagged as a candidate build (which is a requirement for actually being added to an update). However, users were using the new update form as essentially a worksheet, adding builds to the update as they kicked them off, and only submitting the form when they were all built and tagged. The new form does not allow this workflow.

### 2. Adding multiple NVR's at once.
Previously it was possible to paste a comma or space separated list of NVR's into the builds adder, and it would add each as a build to the update.

The newq builds adder only allows a comma separated list of updates to be added. This is because it is possible to search the list of candidate builds (when just normally adding builds) with multiple terms delimited by a space. For example, searching for "kalev fc30 gnome" will return much more limited results. 

Here is a screenshot of the filtering, as well as adding multiple CSV builds:

![screencast](https://user-images.githubusercontent.com/592259/68823045-56622380-06de-11ea-87c9-fd55c5d776da.gif)

**Comment by remicollet** [comment]
In theory, in perfect world, JavaScript is nice and fast

In Practice, in real world, it is not.

The package list refresh may takes a "few" seconds when everything ok (I wait for ~10" this morning for 1 update), and much more when server is under load. And this is really not user friendly

Perhaps you forget there is a lot of Fedora contributors, with very different profiles, so very different needs and expectations:

* some manages a single package and create only a very small number of updates
* some manages large stack, with lot of updates (single packages)
* some manages large stack, with some large updates (multiple packages)
* etc

P.S. and I start to hate this discussion which is mostly "explain your need, I will explain you how to do without", so will stop here.

**Comment by cverna** [comment]
> In theory, in perfect world, JavaScript is nice and fast
> 
> In Practice, in real world, it is not.
> 
> The package list refresh may takes a "few" seconds when everything ok (I wait for ~10" this morning for 1 update), and much more when server is under load. And this is really not user friendly
> 
> Perhaps you forget there is a lot of Fedora contributors, with very different profiles, so very different needs and expectations:
> 
>     * some manages a single package and create only a very small number of updates
> 
>     * some manages large stack, with lot of updates (single packages)
> 
>     * some manages large stack, with some large updates (multiple packages)
> 
>     * etc
> 
> 
> P.S. and I start to hate this discussion which is mostly "explain your need, I will explain you how to do without", so will stop here.

@remicollet I think you are a little bit unfair here. Creating an issue to tell people that the work they have done and the many hours they have spent on it is **terrible** is not a very good way to start a discussion.

As you have mentioned they are different type of users and it is not easy to please everyone, so let's assume positive intent here. We are going to improve the way to create updates we just need to better understand the different pain points.

I also want to point out that Bodhi 5.0 has been in staging for over a month before been deployed in production and we have asked people on the fedora devel list to test it and provide feedback.

**Comment by ryanlerch** [comment]
> The package list refresh may takes a "few" seconds when everything ok (I wait for ~10" this morning for 1 update), and much more when server is under load. And this is really not user friendly

And that would be another pain point. Pre-loading the candidate builds list may take up to 10 seconds.

**Comment by ryanlerch** [comment]
> P.S. and I start to hate this discussion which is mostly "explain your need, I will explain you how to do without", so will stop here.

I'm sorry you got this impression. I am asking you to explain (nice and coherently) your needs and your pain points, so i can help fix the experience. Not sure where you got the impression that my above detailed writeup of pain points was me informing you to "go without".

**Comment by kalev** [comment]
> The newq builds adder only allows a comma separated list of updates to be added.

Ahh great, thanks @ryanlerch!

**Comment by pghmcfc** [comment]
If I try to change the expiry date of an existing expired buildroot override, I get the error message "NVR required" and it doesn't work. I have to create a new override for the same build to get it to work.

**Comment by pypingou** [comment]
@pghmcfc this seems to be related to buildroot overrides and not adding builds to an update. Could you create a separate ticket to be sure it's not lost?
Thanks!

**Comment by mattiaverga** [comment]
@pghmcfc @pypingou no need to open a new ticket: #3710 #3721
