### ISSUE TITLE
It should not be possible to create an update from a side tag for a non rawhide release.

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/bodhi#3783]
https://bodhi.fedoraproject.org/updates/FEDORA-2019-48a3fc7eb5 for example.

**Comment by cverna** [comment]
Currently update with side tags are only supported in rawhide for a few reasons, we want to make sure it works well in rawhide first, and it having side tag working for non rawhide releases requires a bit more work to deal with the updates-testing and updates repo.

So I think we have an issue since you should not have be able to create this update (for F31) using a side tag.

**Comment by igor-raits** [comment]
Aha, So what is the ETA for this in non-rawhide?

**Comment by cverna** [comment]
> Aha, So what is the ETA for this in non-rawhide?

Difficult to say without knowing how well it scale in rawhide first. Let's rollout properly rawhide get some feedback on it then we can look at implementing it for the other releases.

**Comment by igor-raits** [comment]
I see, thanks for the reply . Meanwhile, how I can get those updates pushed through? I can't build them not in side tag.

**Comment by pypingou** [comment]
> I see, thanks for the reply . Meanwhile, how I can get those updates pushed through? I can't build them not in side tag.

Tag them back into the usual tag and ship them in a single update?

**Comment by nphilipp** [comment]
WIth #3800 implemented, I'll close this.
