### ISSUE TITLE
Wrong update instructions for rawhide

### ISSUE THREAD

**Issue by frozencemetery** [fedora-infra/bodhi#3914]
If one manually creates an update for rawhide, it doesn't auto-migrate.  So we need to chase karma, and the "how to install" instructions don't work, which is a problem.

Concretely, I have [this update](https://bodhi.fedoraproject.org/updates/FEDORA-2020-d5d4c21e87).  It happens to be pulling in a side-tag.  The instructions at the top are to run 

```sh
sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-d5d4c21e87
```

As far as I can tell, this will never work because the packages don't go there.  I'm actually not sure what the right invocation is, and would kind of like to know so that I can ask people to test.

**Comment by cverna** [comment]
To fix this we need to make a special condition in the update template for rawhide and modify the install instructions.

Rawhide in bodhi is identified as release that is not composed in bodhi (https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/models.py#L787)

**Comment by mattiaverga** [comment]
Well, not so long ago this was not a problem, since all Rawhide builds were pushed directly in stable, so no updates were left in testing state.

Hiding the update command for all releases not composed by Bodhi would just be a short term fix. The real problem is that there isn't (I'm unaware of) a dnf command to easily install packages of an update pushed in testing from a side tag. It would require dnf to get the build list from the advisory and download packages directly from Koji, since no compose is made.

From what I can see, for Rawhide those packages are tagged with `sidetag-testing-pending`: why it isn't `sidetag-testing`? Is this the right workflow? Or maybe Bodhi is misbehaving here and when an update is created from a sidetag in Rawhide it should be pushed directly in stable?

**Comment by mattiaverga** [comment]
Looking at https://docs.fedoraproject.org/en-US/rawhide-gating/multi-builds/ it seems that sidetag updates should not be left in Testing state. The update reported by the OP should have been moved to stable upon receiving Greenwave result, so definitely Bodhi is misbehaving here.

**Comment by cverna** [comment]
Ha I bet this is cause by https://github.com/fedora-infra/bodhi/issues/3912. If the autotime push is disabled when creating the update, it will get stuck in testing forever.

We need to make sure packager can't disable that option when creating an update.

@frozencemetery can you edit your update and enable auto push based on time ? that should make the update move to stable.

**Comment by frozencemetery** [comment]
@abbra can you update https://bodhi.fedoraproject.org/updates/FEDORA-2020-d5d4c21e87 as suggested by cverna above?

**Comment by abbra** [comment]
Done. Not sure how long will it take to notice or we'll have to wait another couple days.

**Comment by cverna** [comment]
It is now pushed in stable
