### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#3922]
# Summary
* Follow the [developer documentation](https://bodhi.fedoraproject.org/docs/developer/vagrant.html) on how to setup an environment using Vagrant.
* Run the tests confirm that the environment is working.
* Improve the documentation if needed.

## Background
Bodhi is a complex system that interface with many other applications, the development environment based on vagrant allows to have an integrated environment with developer tools available.

There are three main tasks for this ticket:

## Follow setup instructions for a development environment

Run through the existing [documentation](https://bodhi.fedoraproject.org/docs/developer/vagrant.html) to set up a development environment. Completing this helps you iterate new changes and test them. When you complete this, post a screenshot of bodhi running locally in your browser. 💻 📷

## Run the tests to confirm that the environment is working.

Once you have the vagrant environment running, you can run the unit-tests and integration tests. This is important because it will allow you to check if the changes you make to Bodhi works.

## Improve documentation if needed

If everything correctly works, you don't need to do anything more. 💯

If the steps didn't work for you, compare what you did change to get it working to the documentation. If something is unclear or a step is missing, submit a pull request with the improvement. Additions don't need to be long – it's better to write in a more direct and simple way.

**Comment by StarWonder67** [comment]
@cverna Is there any public chat forum where I can reach out to the mentors? I am an outreachy applicant and would like to contribute to this project.

**Comment by cverna** [comment]
> @cverna Is there any public chat forum where I can reach out to the mentors? I am an outreachy applicant and would like to contribute to this project.

@StarWonder67 yes you can join our IRC channel using the riot.im app https://riot.im/app/#/room/#freenode_#bodhi:matrix.org

**Comment by karmadolkar** [comment]
hello @cverna ! I'm Karma Dolkar from Indian Institute of Technology, Roorkee (India). I'm an Outreachy 2020 applicant and very keen to contribute to this project.

Here's a screenshot of Bodhi running locally in my browser: 
 
![Screenshot from 2020-03-08 00-29-43](https://user-images.githubusercontent.com/48379515/76150812-51354400-60d4-11ea-83bc-8a4ac9df0f4b.png)

**Comment by karmadolkar** [comment]
In my opinion, the documentation should include commands specific to commonly used OS, and not just Fedora (example: libvirtd is not a service in Ubuntu that requires enabling). I had to Google a bit regarding the Ubuntu commands so I thought I'd share a suggestion. :smile:  @cverna

**Comment by richardgreg** [comment]
### For setting up development environment, these steps can be helpful if you're having issues with libvirt or wish to use virtualbox instead.

Make sure you have [vagrant](https://www.vagrantup.com) and [virtual box](https://www.virtualbox.org/wiki/Downloads) installed on your computer.

You don't have to use `sudo` to install packages. I find that it can lead to complexities.
Instead of `dns` use `brew install package-name` to install packages like `ansible` and `libvirt`.

Use the cmd `vagrant plugin install plugin-name` to install plugins like `vagrant-sshfs vagrant-libvirt`

Clone the projects [repo](https://github.com/fedora-infra/bodhi) and `cd` into `bodhi`.

Open the `Vagrantfile` with your favourite code editor.

Go to this [site](http://fedora.mirror.liquidtelecom.com/fedora/linux/releases/30/Cloud/x86_64/images/) and copy the url of the last image or this `http://fedora.mirror.liquidtelecom.com/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-30-1.2.x86_64.vagrant-virtualbox.box`, and replace [this line](https://github.com/fedora-infra/bodhi/blob/develop/Vagrantfile#L40) in your `Vagrant` file. Also change the value of `config.vm.box_download_checksum` to `83b8eb3e12a764a5633e330fc8fe483f202c9df1e8107e6b719d00bf0b22b376`

Change `bodhi.vm.provider` from libvirt to virtualbox.

Delete or comment out the following variables and their values: `domain.cpu_mode` `domain.graphics_type` `domain.video_type` `domain.volume_cache`.

While in your projects home directory, run `vagrant up --provider virtualbox`. Your system should begin downloading the vagrant environment. Do not panic if you see any errors in red at the end. Just read and understand it.

Run `vagrant provision`. All your dependencies should download. This can take a while depending on your internet speed.

Enter the cmd `vagrant ssh`. You should be logged into your development environment and met with a welcome message.

Happy hacking.

P.S. Since this was trial and error, the instruction's not perfect and inputs are welcome, especially regarding any package that is not necessary.

**Comment by StarWonder67** [comment]
@richardgreg Can you please help me out with setting the environment on Windows system? I am getting the following error message even when I have installed the sftp server. 
![err3](https://user-images.githubusercontent.com/43103550/76163135-acfddc80-6169-11ea-9d8e-04d63a104fe7.png)

**Comment by karmadolkar** [comment]
hello @richardgreg . I did as you instructed and ended up with the Welcome message! :smile: . Here's the screenshot:
![Screenshot from 2020-03-08 21-33-42](https://user-images.githubusercontent.com/48379515/76166461-be081700-6184-11ea-9202-2f3a72862776.png)

**Comment by richardgreg** [comment]
@StarWonder67 I'm not very familiar with the windows OS. Sorry I can't be of much help.

**Comment by cverna** [comment]
> In my opinion, the documentation should include commands specific to commonly used OS, and not just Fedora (example: libvirtd is not a service in Ubuntu that requires enabling). I had to Google a bit regarding the Ubuntu commands so I thought I'd share a suggestion. smile @cverna

If you can open a Pull Request to add that to the documentation, I would be happy to review it :smile:

**Comment by cverna** [comment]
> @richardgreg Can you please help me out with setting the environment on Windows system? I am getting the following error message even when I have installed the sftp server.
> ![err3](https://user-images.githubusercontent.com/43103550/76163135-acfddc80-6169-11ea-9d8e-04d63a104fe7.png)

I think you will need to install [cygwin](https://www.cygwin.com/) to provide you with a Linux like terminal and utilities. The vagrant-sshfs plugin seems to look for it on windows (https://github.com/dustymabe/vagrant-sshfs/pull/34/files)

**Comment by Oishika-Pradhan** [comment]
Hi, @cverna . I am Oishika Pradhan, an Outreachy 2020 aspirant. Here is a screenshot of Bodhi running on my browser.
![Screenshot from 2020-03-09 19-06-37](https://user-images.githubusercontent.com/23234376/76218031-7b544680-6239-11ea-9d98-e2b17903c927.png)

**Comment by jennizalwango** [comment]
hello @cverna
l am an outreachy applicant and would like to contribute to this project , l am still setting up the development environment l have been able to install the Virtualbox and vagrant however l get an error when installing libvirt l am using ubuntu as an OS
Here is the error l get every time l reach at this step:
![Screenshot from 2020-03-10 06-17-19](https://user-images.githubusercontent.com/43774983/76276434-dd8f6480-6296-11ea-9e70-3127c88f22ce.png)

**Comment by cverna** [comment]
@jennizalwango if you have virtualbox you will not need to use libvirt :-). You can check @richardgreg comment on how to setup the environment with vagrant and virtualbox (https://github.com/fedora-infra/bodhi/issues/3922#issuecomment-596193046)

**Comment by jennizalwango** [comment]
hello @clement
Actually l checked it out and l still bumped into some error l am not sure
if its because of the OS am using

**Comment by ephraimbuddy** [comment]
Hi, @cverna , I am Ephraim Anierobi, an Outreachy aspirant, here's a screenshot of bodhi running on my browser.
![Screenshot from 2020-03-11 07-19-18](https://user-images.githubusercontent.com/4122866/76388327-2a437000-6369-11ea-8f92-291c6dc6845e.png)

**Comment by jennizalwango** [comment]
Hi @cverna, l have been able to run bodhi locally l must say it has come with a lot of learning which is a good thing and something l love below is the screenshot. However, l would also suggest we provide documentation on how to set up the development environment on different Operating Systems. Personally, l am using ubuntu and it has been challenging and since this is something @karmadolkar talked about as well, I suggest that we could pair program on this and get it done faster.
![Screenshot from 2020-03-12 11-19-49](https://user-images.githubusercontent.com/43774983/76501890-25a7b600-6454-11ea-81ed-71e749500c0d.png)

**Comment by madham32** [comment]
![image](https://user-images.githubusercontent.com/47317143/76561694-a0f58000-64c5-11ea-8c1a-a2f85a957bde.png)
Hi! I'm Hammad, an Outreachy aspirant from Pakistan. I was wanting to apply myself in this project but I can't get past this error. Any help would be appreciated!

**Comment by richardgreg** [comment]
@madham32 the image you're downloading uses libvirt for virtualisation. You can follow [this](https://github.com/fedora-infra/bodhi/issues/3922#issuecomment-596193046) instruction I provided if you wish to use VirtualBox as your provider. I don't think it's exclusive to macOS.

**Comment by madham32** [comment]
![Screenshot from 2020-03-15 15-34-12](https://user-images.githubusercontent.com/47317143/76696033-bd9ddd80-66a8-11ea-8e19-6551d82dc152.png)
I tried that and got this. Any suggestions?

**Comment by richardgreg** [comment]
@madham32 is the plugin `vagrant-sshfs` installed?

**Comment by madham32** [comment]
![image](https://user-images.githubusercontent.com/47317143/76699225-4464b180-66cd-11ea-92cc-28cbe7145b28.png)
I tried and got this

**Comment by madham32** [comment]
I tried doing that as well and got this

![image](https://uScreenshot from 2020-03-15 15-01-35ser-images.githubusercontent.com/47317143/76699283-fac89680-66cd-11ea-8f11-54c5cb7bc80b.png)

**Comment by madham32** [comment]
![image](https://user-images.githubusercontent.com/47317143/76699295-0b790c80-66ce-11ea-87d2-7d037c5a847a.png)
I tried that as well and got this

**Comment by richardgreg** [comment]
@madham32 which cmd did you enter that produced the error?

**Comment by shivani-1521** [comment]
Hi, @cverna , I am Shivani Singh an Outreachy aspirant. Here is a screenshot of bodhi running on my browser. 
![Screenshot_2020-03-23 Fedora Updates System](https://user-images.githubusercontent.com/28950304/77303966-ca11de00-6d19-11ea-87b8-2401dbd83622.png)

**Comment by nnatarajan** [comment]
Hi @cverna,  

Here is a screenshot of bodhi running locally in my browser. Please let me know if I should prioritize any specific issue. 

Best, 
Natasha Natarajan
Outreachy Applicant

<img width="1642" alt="Screen Shot 2020-03-25 at 2 13 23 PM" src="https://user-images.githubusercontent.com/20606687/77581758-e8a3e080-6ea3-11ea-9da7-3f1ea4ffdbc2.png">

**Comment by cverna** [comment]
> Hi,
> 
> Thank you @cverna and @richardgreg for your instruction. I am attempting to use virtual box on mac.
> 
> Can you advise on bodhi-dev login and password for the virtual box?
> 
> If not available, please advise on best process for mac.
> 
> Best,
> Natasha

You should not need to provide a login or a password, to connect to the virtualbox you can use `vagrant ssh` from a terminal session.

**Comment by nnatarajan** [comment]
> > Hi,
> > Thank you @cverna and @richardgreg for your instruction. I am attempting to use virtual box on mac.
> > Can you advise on bodhi-dev login and password for the virtual box?
> > If not available, please advise on best process for mac.
> > Best,
> > Natasha
> 
> You should not need to provide a login or a password, to connect to the virtualbox you can use `vagrant ssh` from a terminal session.

My virtual box shown here in the first screenshot is requiring a login and password:

Separately, when I attempted to brew install ansible and libvirt on terminal, I received the error in the second screen shot:

<img width="452" alt="Screen Shot 2020-03-27 at 9 52 50 AM" src="https://user-images.githubusercontent.com/20606687/77775060-a4365300-7011-11ea-9dc2-84772581a739.png">

<img width="719" alt="Screen Shot 2020-03-27 at 10 04 23 AM" src="https://user-images.githubusercontent.com/20606687/77776170-37bc5380-7013-11ea-8ae5-d3591aefbac6.png">
