### ISSUE TITLE
RFE: Autoclose Rawhide bugs

### ISSUE THREAD

**Issue by voxik** [fedora-infra/bodhi#3925]
I have just build rubygem-its. Because I have referenced bugzilla ticket in the changelog as well as in git log \[[1]\], I would expect Bodhi to associate this ticket with the Bodhi update \[[2]\] and handle the bug properly, i.e. close it as soon as the update lands in Rawhide. Unfortunately, this is probably not the case ATM.

[1]: https://src.fedoraproject.org/rpms/rubygem-rspec-its/c/3714b55268393f5398de3a56db57e7b19a32a2c7?branch=master
[2]: https://bodhi.fedoraproject.org/updates/FEDORA-2020-60bb269473

**Comment by mattiaverga** [comment]
This can be implemented in the code that SHOULD automatically output the changelog in the release notes, added since v5.0: https://github.com/fedora-infra/bodhi/commit/54210f7e1932b763103ad0a38c3bb818862bc081

But it seems this is not working at all (I've never seen changelog entries in any update so far). @ryanlerch do you have any idea why we don't get any output from `generate_changelog()`?

**Comment by mattiaverga** [comment]
It seems koji's `getLatestBuilds()` only return the latest build, not a list of latest builds, so `Build.get_latest()` always returns nothing.

I've opened a PR to Koji to correct this behavior: https://pagure.io/koji/pull-request/2015
