### ISSUE TITLE
bodhi fails to build with Python 3.9: _dummy_thread and dummy_threading modules have been removed

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#4007]

**Comment by hroncok** [comment]
The suggested usage of `dummy_threading` is:

```python
try:
    import threading
except ImportError:
    import dummy_threading as threading
```

To support installations without the threading module.

https://docs.python.org/3.6/library/dummy_threading.html

Installations without the threading module are no longer possible since Python 3.7:

https://docs.python.org/3.7/library/dummy_threading.html

And hence this module was removed from Python 3.9.

However, the tests here use it in a different (possibly unsupported) way:

https://github.com/fedora-infra/bodhi/blob/23457599202a94ba9f4dff303b5e1396d5b35678/bodhi/tests/server/tasks/test_composer.py#L156-L164

This is either a neat trick, or a total hack, depending on the perspective.

**Comment by cverna** [comment]
Yeah and by looking at the comment I am not 100% sure how we are going to replace that :smile:

**Comment by hroncok** [comment]
We need a proper threading mock that makes sure no threads actually run. I've googled a bit but I cannot find anything. @vstinner, do you have some idea?

**Comment by hroncok** [comment]
Let's see if we can mock `ComposerThread` to have `start()` that simply calls `self.run()`.

**Comment by hroncok** [comment]
OK, I am officially not able to run the tests from git, but this passes in rmbuild:

```patch
diff --git a/bodhi/tests/server/tasks/test_composer.py b/bodhi/tests/server/tasks/test_composer.py
index 28b1e82..e6afdcd 100644
--- a/bodhi/tests/server/tasks/test_composer.py
+++ b/bodhi/tests/server/tasks/test_composer.py
@@ -19,7 +19,6 @@ from unittest import mock
 from urllib.error import HTTPError, URLError
 import urllib.parse as urlparse
 import datetime
-import dummy_threading
 import errno
 import json
 import os
@@ -161,7 +160,8 @@ class TestComposer(base.BasePyTestCase):
         # Mock was not able to make this change since the __bases__ attribute cannot be removed, but
         # we don't really need this to be cleaned up since we don't want any tests launching theads
         # anyway.
-        ComposerThread.__bases__ = (dummy_threading.Thread,)
+        ComposerThread.start = lambda self: self.run()
+        ComposerThread.join = lambda self, timeout=None: None
         test_config = base.original_config.copy()
         test_config['compose_stage_dir'] = self._new_compose_stage_dir
         test_config['compose_dir'] = os.path.join(self._new_compose_stage_dir, 'compose')
```

Do you want to rework this to use mocking, or is it fine if I submit this as a PR (with adapted comment).

**Comment by cverna** [comment]
:+1: that looks good to me, thanks for looking at it

**Comment by hroncok** [comment]
https://github.com/fedora-infra/bodhi/pull/4026
