### ISSUE TITLE
sidetag user experience can be improved

### ISSUE THREAD

**Issue by abbra** [fedora-infra/bodhi#4014]
It seems that only a creator of a sidetag can submit it as a bodhi request, however, there is no way to assign more than one person to a sidetag management. As result, if sidetag creator does not possess permissions to _all_ components built in the sidetag, nobody will be able to submit the resulting request to bodhi.

I encounter this twice already when doing complex updates of packages with dependent ABI changes.

I'd sugges several changes, not necessarily all falling into bodhi alone:
- allow side-tag creator to add more users to manage the sidetag. Right now they cannot edit sidetag at all, they cannot do anything with it
- allow proven packagers to submit sidetags they do not own
- if a packager has rights to all packages built in sidetag, allow them to submit the sidetag to bodhi

It should not matter who created the sidetag, only a content of the tag should influence who can submit it.

**Comment by nphilipp** [comment]
@abbra I forgot to ask that on IRC, did you attempt to create the update using the `bodhi` CLI tool, too? I ask because the code looks as if this is only an issue in the web UI, it only offers side tags created by the logged in user (otherwise the list would be pretty long).

@ryanlerch What do you think, if my assumption is true, should we offer an additional way to enter a side tag manually so people could create updates from side tags they don't own?

**Comment by abbra** [comment]
@nphilipp I haven't tried the CLI tool. Next time let me not forget about it ;)
