### ISSUE TITLE
Allow users to have their personal data removed from Bodhi

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4022]
If I'm not mistaken, one of the key points of GDPR is that users can have their personal data removed from site database.
Currently Bodhi fetches some personal data from FAS and stores them in its database. The privacy policy refers to the general Fedora privacy policy, where the user can open a ticket in Pagure and have their data removed from FAS. But that doesn't cover removing user data in other related databases like Bodhi.

I think we should provide a page where the user can have a look at what personal data about them we memorize in our database, along with a service that allows the user to delete their data from Bodhi.
When deleting the user data we can:

- set the username to something like `removed-user-<ID>` 
- nullify email
- remove the user from any group

This should be enough to not break other Bodhi stuff like comments and updates associated to the user.
Maybe, we also should make possible for users member of some restricted group (fedora-infra, legal, ...?) to use this service to easily remove other users from the database. Otherwise the service must allow a user to remove only their own account.
If a user removes their data and subsequently login back into Bodhi, a new user in Bodhi database will be created, so the user will have lost their privileges on already created updates.

Let me know if you have any other thoughts, when ok I will start working on this.

**Comment by cverna** [comment]
Hey @mattiaverga so we do not delete personal data from bodhi because we have a "legitimate interest" of keeping these data. In bodhi's case it is a valuable information to know who created an update.

However to comply to GDPR we are providing a "Subject Access Request" (SAR) which gives the requester all the informations we have about them. This is currently done by https://github.com/fedora-infra/bodhi/blob/develop/bodhi/server/scripts/sar.py.

I hope that helps :smile:

**Comment by mattiaverga** [comment]
Oh, ok. So we don't need this, I'll close the ticket!
