### ISSUE TITLE
Update was not auto-pushed to stable after 7 days

### ISSUE THREAD

**Issue by morxa** [fedora-infra/bodhi#4042]
[This update](https://bodhi.fedoraproject.org/updates/FEDORA-2020-189a42d65a) should have been pushed to stable after 7 days, but wasn't. I'm not sure if this was a one time issue.

It received +2 karma, the threshold was +3. So it received feedback, but not enough to reach the threshold. Maybe it's related to that?

**Comment by QuLogic** [comment]
[Here](https://bodhi.fedoraproject.org/updates/FEDORA-2020-d5cd2e2fa6)'s a similar update that received 2 karma, sent me a notification that it can be submitted for stable (even though limit is +3), and then never submitted it automatically when 7 days came around.

**Comment by QuLogic** [comment]
[Here](https://bodhi.fedoraproject.org/updates/FEDORA-2021-0691392fdd)'s another update that says it can be pushed after 2 (not 3) karma, then never auto-pushed after 3 days.

**Comment by QuLogic** [comment]
@nirik said in the infra ticket that the logs said:
> FEDORA-2021-0691392fdd has already the comment that it can be pushed to stable - bailing

And yes, the [second check](https://github.com/fedora-infra/bodhi/blob/348c3072a5c83106fad573bc35d168b27d2f7b34/bodhi/server/tasks/approve_testing.py#L69) of `approve_testing` does look for an existing comment from Bodhi. Automatic pushing to stable occurs [later in this function](https://github.com/fedora-infra/bodhi/blob/348c3072a5c83106fad573bc35d168b27d2f7b34/bodhi/server/tasks/approve_testing.py#L96). This means that Bodhi will never automatically push if it's left a comment for the packager due to some other condition than the automatic one.

**Comment by ryanlerch** [comment]
This PR / Issue was included in the 5.7.0 release of Bodhi, and is now deployed in Fedora Staging. Please verify and test that this works as expected.

https://bodhi.stg.fedoraproject.org/
