### ISSUE TITLE
Rawhide automatically close bugs when the update reach stable

### ISSUE THREAD

**Issue by cverna** [fedora-infra/bodhi#4067]
We now can associate bugs to a rawhide update but the bugs are not closed when the update reach stable. This is normally done during the daily compose which does not happen in rawhide so we need to probably add that steps to the approve_testing script.

**Comment by mattiaverga** [comment]
We should probably run a work_on_bugs task in the automatic_updates script to fetch the bug title. (also)

**Comment by cverna** [comment]
Since approve_testing is already a celery tasks it is usually not really recommended to call another celery tasks from it. Also we have a modify_bugs method in the Update class that seems to be doing what we want so I went that way.

**Comment by mattiaverga** [comment]
I was suggesting to run the work_on_bugs celery task inside the automatic_updates consumer.
The modify_bugs method is fine, but it only closes the bug in bz. When the bug is added we must fetch the bug title or we will end up with a forever spinning spinner as the bug title like https://bodhi.fedoraproject.org/updates/FEDORA-2020-21cac06005

**Comment by mattiaverga** [comment]
I would add 
```
alias = update.alias
work_on_bugs_task.delay(alias, closing_bugs)
```
at the very end of
https://github.com/fedora-infra/bodhi/blob/45b025b9558ec019fb75846799a9a8d8d81e57e0/bodhi/server/consumers/automatic_updates.py#L193
after the commit.

BTW, the session is already committed or rolled back when `dbsession` gets closed, so that commit() isn't useful, am I right? I think we can change it to be a flush().

**Comment by cverna** [comment]
> I would add
> 
> ```
> alias = update.alias
> work_on_bugs_task.delay(alias, closing_bugs)
> ```
> 
> at the very end of
> 
> https://github.com/fedora-infra/bodhi/blob/45b025b9558ec019fb75846799a9a8d8d81e57e0/bodhi/server/consumers/automatic_updates.py#L193
> 
> after the commit.
> 
> BTW, the session is already committed or rolled back when `dbsession` gets closed, so that commit() isn't useful, am I right? I think we can change it to be a flush().

Yeah that's sound good to me.
