### ISSUE TITLE
Integration tests fail when using pip as the tagrged

### ISSUE THREAD

**Issue by AdamSaleh** [fedora-infra/bodhi#4158]
When running tests, they fail with message:
```
 FAILED: Path doesn't exist: '/usr/local/lib/python3.9/site-packages/bodhi-5.5-py3.9.egg/bodhi/server/migrations'.  Please use the 'init' command to create a new scripts folder.
```

The path it should be looking for it '/usr/local/lib/python3.9/site-packages/bodhi_server-5.5-py3.9.egg/bodhi/server/migrations'

**Comment by mattiaverga** [comment]
It seems more like an error during installation:
`error: urllib3 1.26.1 is installed but urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 is required by {'requests'}`
however, trying in a local virtualenv works:
`Requirement already satisfied: urllib3<1.27,>=1.21.1 in /virtualenvs/piptest-Qo1sd9nT/lib/python3.9/site-packages (from requests) (1.26.2)`

But now everything is broken because of
```
18:09:57  Trying to pull repository docker.io/library/fedora ... 
18:09:57  toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
:-(

**Comment by AdamSaleh** [comment]
I already worked around the requests dependencies issue, by putting it in the setup.py tests_require first :-)

Then I run into yet another problem with alembic in f32 ... I want at least one green integratio run and then I start rewriting the damned thing! :D

**Comment by AdamSaleh** [comment]
@pypingou this is still a problem, my plan is to skip these until I sit down and try to improve these.
