### ISSUE TITLE
Archive the GraphQL to separate branch and remove it from devel

### ISSUE THREAD

**Issue by AdamSaleh** [fedora-infra/bodhi#4162]
One of the issues when packaging Bodhi that @nirik  mentioned is that Bodhi now contains proof-of-concept GraphQL enpoint,
and we don't have it packaged in fedora.

Because both @mattiaverga and @cverna mentioned problems they encountered when packaging it, I propose to just remove it.

Moreover (based on the short talk by @StephenCoady) GraphQL doesn't seem as that of a good fit for Bodhi, i.e. we don't need to optimize for ammount of data sent to client making large, but simple queries over deeply nested data. One advantage over current REST api that GraphQL provides is a formal api definition, but there proably are better tools to provide that. 

The changes seem to be mostly-self-contained, so moving them to separate branch could allow for restarting the initiative, if we figure this is a good idea again and the python ecosystems for GraphQL matures.

What do you think?

**Comment by mattiaverga** [comment]
I've also thought about this solution. It depends what we want and what graphql can do in our usecase. If it can overcome the json serialization problems we encounter when serving API response, it makes sense to continue developing.

I've just requested the branch creation for python-graphql-sqlalchemy and posted the package review request for python-graphql-server (3.0beta2). When approved we can try to move graphql code in Bodhi to use graphql-server+[webob] instead of WebOB-GraphQL and decide about removing graphql from prod if that proves to be a too hard/long task.

**Comment by StephenCoady** [comment]
Just to clarify, I never said that applications like Bodhi are a bad fit at all. You just might not get the same benefit you had hoped for. In general I think it could work well, considering clients only tend to care about a very small subset of data. Its also just a very clean way to serve responses.

That being said I wouldn't be against moving it to a feature branch until its a more complete API.

**Comment by AdamSaleh** [comment]
Yeah, I should clarify that it was *my opinion* based on *Steven's description of GraphQL* (and not i.e. my experience with it in anger) :-)

**Comment by cverna** [comment]
> One of the issues when packaging Bodhi that @nirik mentioned is that Bodhi now contains proof-of-concept GraphQL enpoint,
> and we don't have it packaged in fedora.

It does not really need to be packaged in Fedora, Bodhi (server) is currently deployed directly from git in OpenShift and in my opinion that should be the way forward. I don't think packaging the server side as an rpm is valuable. But I am happy to be wrong :-).

The graphql endpoint is actually live in prod https://bodhi.fedoraproject.org/graphql

> 
> Because both @mattiaverga and @cverna mentioned problems they encountered when packaging it, I propose to just remove it.
> 
> Moreover (based on the short talk by @StephenCoady) GraphQL doesn't seem as that of a good fit for Bodhi, i.e. we don't need to optimize for ammount of data sent to client making large, but simple queries over deeply nested data. One advantage over current REST api that GraphQL provides is a formal api definition, but there proably are better tools to provide that.
> 
> The changes seem to be mostly-self-contained, so moving them to separate branch could allow for restarting the initiative, if we figure this is a good idea again and the python ecosystems for GraphQL matures.

I have a branch on my fork that remove the code for packaging https://github.com/cverna/bodhi/commit/84c67e4b93a5e68ba2dba304e2094ac63f96b980. It should be trivial to add this as a patch file for now.

> 
> What do you think?

I am not much involved in Bodhi any more so take my opinion lightly :), I think there is value in having Graphql in Bodhi but that would be a long term investment both the UI and the cli would benefit from using a Graphql endpoint instead of the current APIs but that will require some effort. So the question is how much do we plan to work on Bodhi ?

**Comment by mattiaverga** [comment]
>  So the question is how much do we plan to work on Bodhi ?

Is there any alternative?
Bodhi is a critical component in Fedora packaging workflow. So, in my opinion, it should be (actively) maintained by the infrastructure team. Is this is not possible due to lack of workforce, the Fedora community should choose between putting together a group of skilled volunteers to maintain Bodhi or drop it entirely from the packaging workflow.
How other linux distributions work? Are there more pros or more cons to continue maintaining Bodhi? Is there any chance to develop something new that can trigger RHEL interests?
I think a discussion should be opened within the Fedora community/FESCO.

**Comment by nirik** [comment]
IMHO there's no need for discussion, this has to be an application CPE maintains (with any help from the community). 

Perhaps we could table the GraphQL stuff for now and get things back to a state where we can do quick bugfix releases, then look at filing a CPE initiative to Do the GraphQL work? That would allow us to weigh all the advantages, get a small team to do the work, etc?

**Comment by mattiaverga** [comment]
Just an update: the library we use for GrapQL APIs (graphene) it's nearly dead upstream, graphene v2 will not work with Python 3.10 landed in Rawhide, GraphQL work here on Bodhi seems to have been abandoned.
We need to make a choice.
