### ISSUE TITLE
bodhi commands fail: Token required but invalid

### ISSUE THREAD

**Issue by martinpitt** [fedora-infra/bodhi#4237]
I'm trying to waive some invalid/missing test results. This has worked fine in the past, but today something in the authentication system is broken:
```
bodhi updates waive --user martinpitt --test fedora-ci.koji-build.tier0.functional FEDORA-2021-05b3e69178 'regression in libvirt, will investigate/report  separately'
Waiving unsatisfied requirements: fedora-ci.koji-build.tier0.functional
Password: 
Bodhi failed to send POST request to WaiverDB at the following URL "https://waiverdb.fedoraproject.org/api/v1.0/waivers/". The status code was "401". The error was "{'message': 'Token required but invalid'}".
```

I triple-checked that the password is correct (copy&pasted from keepass database), and I also tried with the "cockpit" account. This also happens after removing ~/.fedora/ (i.e. no stale `openidbaseclient-sessions.cache`).

**Comment by mattiaverga** [comment]
I think it refers to the token that Bodhi backend uses to authenticate in waiverdb.
It seems that for some reason the token we have configured in Bodhi config doesn't work anymore, maybe it's expired or has been removed from waiverdb.

Can you open a ticket on [Fedora infra](https://pagure.io/fedora-infrastructure/issues) so that someone over there can have a look into this?

**Comment by martinpitt** [comment]
Sure! Opened https://pagure.io/fedora-infrastructure/issue/10064
