### ISSUE TITLE
bodhi is not moving the modular builds from testing to stable when a build goes stable

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/bodhi#4274]
RelEng ticket has all the details that are needed:

https://pagure.io/releng/issue/8074

Its still happening in f35 release as well

```
# dnf module info perl:5.32 | grep -E '^(Version|Repo)'
Version          : 3520210922083143
Repo             : fedora-modular
Version          : 3520210922083143
Repo             : updates-modular
Version          : 3520210922083143
Repo             : updates-testing-modular
```

And I dont see a untagged from f35-modular-updates-testing tag in koji history when it went to stable:

```
$ koji list-history --build perl-5.32-3520210922083143.ab7e7bfe
Wed Sep 22 05:44:57 2021 perl-5.32-3520210922083143.ab7e7bfe tagged into f35-modular-updates-candidate by mbs/mbs.fedoraproject.org
Wed Sep 22 06:09:02 2021 perl-5.32-3520210922083143.ab7e7bfe tagged into f35-modular-signing-pending by bodhi
Wed Sep 22 06:10:11 2021 perl-5.32-3520210922083143.ab7e7bfe untagged from f35-modular-signing-pending by autopen
Wed Sep 22 06:10:11 2021 perl-5.32-3520210922083143.ab7e7bfe tagged into f35-modular-updates-testing-pending by autopen
Wed Sep 22 14:00:16 2021 perl-5.32-3520210922083143.ab7e7bfe untagged from f35-modular-updates-candidate by bodhi
Wed Sep 22 14:00:16 2021 perl-5.32-3520210922083143.ab7e7bfe tagged into f35-modular-updates-testing by bodhi [still active]
Wed Sep 22 14:00:23 2021 perl-5.32-3520210922083143.ab7e7bfe untagged from f35-modular-updates-testing-pending by bodhi
Thu Sep 30 06:07:00 2021 perl-5.32-3520210922083143.ab7e7bfe tagged into f35-modular-updates-pending by bodhi
Thu Sep 30 22:13:44 2021 perl-5.32-3520210922083143.ab7e7bfe tagged into f35-modular by bodhi [still active]
Thu Sep 30 22:13:50 2021 perl-5.32-3520210922083143.ab7e7bfe untagged from f35-modular-updates-pending by bodhi
```

**Comment by mattiaverga** [comment]
mmm... this happens for all update types when the release is branched and not yet composed by Bodhi.
I see all "problematic" builds have tags like `f35`+`f35-updates-testing` or `f35-modular`+`f35-modular-updates-testing`, while other "sane" updates have `f35-updates` or `f35-modular-updates`.

I think the bug lies in
https://github.com/fedora-infra/bodhi/blob/f13fc203aa31419a3cc5f0fa6f03b715566ab25b/bodhi/server/tasks/approve_testing.py#L157-L162

But I'm not sure where the `-updates-testing` tag is removed for releases composed by Bodhi. I cannot find any line in the composer task that removes that tag. I remember there was some infra app which does some magic about tagging, but I don't remember what it is... maybe there's some magic that automatically removes the `-updates-testing` tag when a build is tagged under `-updates` and since for branched releases the builds go directly to the stable tag that magic doesn't happen?

**Comment by mattiaverga** [comment]
I think I got it: the composer uses `koji.moveBuild`
https://github.com/fedora-infra/bodhi/blob/f13fc203aa31419a3cc5f0fa6f03b715566ab25b/bodhi/server/tasks/composer.py#L606

Perhaps we should do the same in the approve_testing task.
