### ISSUE TITLE
bodhi randomly throws "NoSuchColumnError bugs.id" server errors for various queries

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/bodhi#4287]
Since the last time bodhi instance at bodhi.fedoraproject.org was updated, I'm getting lots of these error messages when querying bodhi for various things:

```
{ errors:
    [
        {
            "location": "body",
            "description": "Could not locate column in row for column 'bugs.id'",
            "name": "NoSuchColumnError"
        }
    ],
    status: "error"
}
```

I cannot find a way to reliably reproduce this error, as it does not occur reliably for any particular query, but instead randomly for any query.

**Comment by QuLogic** [comment]
It occurs quite regularly for creating new updates as well. Probably the chances increase if you have multiple releases in the update page (that need to be split into multiple updates), because then the code actually posts some notifications and goes to a different page than if it were a single package release.

**Comment by nirik** [comment]
@AdamSaleh Can we get a new release with @mattiaverga 's fix rolled out soon? Folks keep hitting this. :)

**Comment by AdamSaleh** [comment]
Ack. Working to have it on staging today.
