### ISSUE TITLE
After 5.7.3 release, some updates with bugzillas never finish loading

### ISSUE THREAD

**Issue by AdamSaleh** [fedora-infra/bodhi#4317]
Cause of the issue is not yet known.

One such example: https://bodhi.fedoraproject.org/updates/FEDORA-2021-c2b61f2725

Currently investigating.

Will @mattiaverga have some idea?

**Comment by AdamSaleh** [comment]
Running in bodhi-shell:
```
u = m.Update.query.filter_by(alias='FEDORA-2021-c2b61f2725').one()
[b.update_details() for b in u.bugs]
m.Session().commit()
```

did manually fix the issue. This could suggest problem is somewhere in celery-worker?

**Comment by mattiaverga** [comment]
@AdamSaleh yeah, I know the cause: creating sidetag rawhide updates never calls the work_on_bugs celery task.
We should find an appropriate place where to call the task for this type of updates, like we do for the other, or we can find a place where to call it for all types (maybe in the update.__init__() method, which I think it's the only common place for all).

This has been on my todo list for a while, but always postponed since it's not causing any real issue apart of the missing title in the web UI (the loading animation is just a gif, nothing is really loading in the background).

**Comment by AdamSaleh** [comment]
Good! I will mention it to releng guys, that this shouldn't signify an issue, more of a UX problem.

I wonder if we should have such hook directly in the model somewhere? Or is that a bad idea?
