### ISSUE TITLE
It's time to move away from the term "karma"

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/bodhi#4321]
I've always been somewhat uncomfortable with our use of the term "karma" in Bodhi.[^1] This is an important philosophical concept and linked to many people's religious beliefs. I think our use of it for whether a package works trivializes that in a... (as my kids would say) "pretty cringy way".

It's also not actually very descriptive. What the heck does it actually have to do with the principle of karma, or even various western interpretations and derivations?

I suggest we change this to just "feedback".

 I know it's wired into the message bus and probably other things that aren't easy, quick changes, but we could:

1. First pass, change the term in the UI and docs
2. Change it under the hood in bodhi itself
3. Change it in the message bus and everything that listens to that
4. Change things like badges and so on

The last parts might take a long time, but ... can we do the first more quickly?

[^1]: I'm not going to slippery-slope about "bodhi" as a name itself right now, although it's also worth being conscientious there.

**Comment by james02135** [comment]
Propose changing "karma" to "votes"

**Comment by mattdm** [comment]
Sure, "votes" works for me.

**Comment by mattiaverga** [comment]
"vote" just seems a politically oriented term to me, I would have proposed "grade", but I'm not English native here...

**Comment by james02135** [comment]
Will we put it to the rest of the community?

**Comment by james02135** [comment]
# Story

As a community member,
I want to remove the term "karma" from Bodhi due to it's religious connotations and misuse here. 

# Acceptance Criteria

- [ ] The term "karma" is replaced with the term "vote/votes/voting" in the docs
- [ ] The term "karma" is replaced in the codebase
- [ ] Research where the term is used within the message bus
- [ ] Make the community aware of the change, and help identify where the term has been implemented
- [ ] Forewarn the Badges ARC Investigation Team of the change so that they can include that in the initiative planning

# Background

Movement away from utilizing religious terms in an insensitive way

# Definition of Done

- [ ] All instances of the term "karma" have been replaced with "vote"
- [ ] Communication in the form of a blog post to the community to make everyone aware of the change

**Comment by rathann** [comment]
How about simply "comment" instead of "vote"? Comments can be positive and negative, too.

**Comment by mattiaverga** [comment]
Whatever term is used to replace "karma", whoever wants to submit such change needs to consider a transition period when "karma" is deprecated, but still present aside the new term in messages and json output, otherwise many dependent tools will blow up.

**Comment by james02135** [comment]
@rathann "Comment" works for me too. I think this needs to go up for a vote so at the very least we can move forward with whatever term the majority favours. 

@mattiaverga That's exactly why this issue has stalled. The replacement of the term "karma" might mean a major version change, and carry the full weight of what that means for any applications downstream

**Comment by natanael-b** [comment]
Why not `3rd-newton-law`?

**Comment by mattiaverga** [comment]
The discussion took place at
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/5LQGAAS634WUFMIV56PDFQQY6I764JSA/
and
https://discussion.fedoraproject.org/t/moving-away-from-the-term-karma-in-bodhi/136292

The poll hosted on Fedora Discussion showed that over 2/3 prefer to maintain the "karma" terminology.
