### ISSUE TITLE
cannot see "re-trigger test" in bodhi

### ISSUE THREAD

**Issue by psklenar** [fedora-infra/bodhi#4354]
I cant see the button in bodhi:  "re-trigger test" and 'waive test results'

I set up Fedora CI + created a few tests for rpm bind. When there is a bind-update
I cant see the button in bodhi:  "re-trigger test" and 'waive test results'
for ex:
https://bodhi.fedoraproject.org/updates/FEDORA-2022-f727b70e0f

**Comment by psklenar** [comment]
![image](https://user-images.githubusercontent.com/25981983/151140100-afa74389-759f-4a1b-8fd4-a38be995daa0.png)

**Comment by mattiaverga** [comment]
Only who has edit privileges on the update can see the "re-trigger tests" button.
That means:
- the user who "owns" the side-tag and created the update
- any user who have commit access to **all** the packages in the update
- any provenpackager

I see from the screenshot you hadn't edit privileges (no "edit" button on top right), that's why you couldn't re-trigger or waive tests.

**Comment by mattiaverga** [comment]
I hope I've answered your question here

**Comment by thrix** [comment]
@mattiaverga the use case here is that there are RHEL QEs who are not packagers, can we create a new group for them?

**Comment by mattiaverga** [comment]
The "waive tests" and the "re-trigger tests" services are currently using the same ACLs used for allow editing an update.
I suppose we can add a new ACL to give members of `qa` group access to those functions, without the need to have them allowed for full editing.
I'll open a new ticket to track the RFE

**Comment by psklenar** [comment]
@mattiaverga Thank much, it would be nice for QE to be able to retrigger tests in case of any test failure or test maintenance.
