### ISSUE TITLE
Updates ejected from the push

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4363]
We're seeing a lot of updates getting stuck with the error "ejected from the push because Cannot find relevant tag".
I suppose the problem is in the composer tasks order: we move builds from one tag to another, then we remove pending tags, then the compose is performed and finally we update the update status.
Lately I'm seeing a lot of builds are being correctly moved between tags, but then the update status is not updated, so the next run Bodhi retries to compose the build, but it doesn't find the correct tags.

I have no idea why in recent times Bodhi started to behave so badly (these errors started before the recent version upgrade), but it's becoming a nightmare.

**Comment by nirik** [comment]
This issue is very very likely the koji tagging issue ( https://pagure.io/koji/issue/3220 ). 

ie, bodhi says 'move these packages from tag a to tag b' and some of them return a failure of 'already tagged', but yet it worked. 
Bodhi thinks the tagging failed, but really it worked, so now they aren't in the right tags anymore. 

I am not sure how bodhi can deal with this aside perhaps from checking tags when resuming and using that information?

**Comment by mattiaverga** [comment]
Ejecting an update from a compose shouldn't cause the entire compose to fail, but this seems what's happening now. I was unable to determine what's causing this in the code, @nirik are the composer logs available somewhere?

**Comment by nirik** [comment]
We only keep 14 days of updates composes, so I don't think we have them anywhere. ;( 

We may be able to simulate it in staging by making an update, then locking or setting a perm on the tags bodhi doesn't have and see what happens?
