### ISSUE TITLE
Fix the specfiles and RPMs since the split of packages

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/bodhi#4378]
We are now building RPMs automatically with each PR, but the layout of the RPMs is slightly different to what we had before.

Previously, we had one package (srpm) that produced multiple sub-packages,that is:

* bodhi-client-5.7.4-0.fc34.noarch.rpm
* bodhi-composer-5.7.4-0.fc34.noarch.rpm
* bodhi-docs-5.7.4-0.fc34.noarch.rpm
* bodhi-server-5.7.4-0.fc34.noarch.rpm
* python3-bodhi-5.7.4-0.fc34.noarch.rpm
* python3-bodhi-client-5.7.4-0.fc34.noarch.rpm
* python3-bodhi-messages-5.7.4-0.fc34.noarch.rpm

the way it is set up now (probably incorrectly because i did it) is 3 srpms / specfiles producing each module as a package: (bodhi-client, bodhi-server, and bodhi-messages)

We need to decide if we still want to split out composer and do that, and also the python3* packages too

**Comment by ryanlerch** [comment]
So have been doing some looking at this one, and wondering if this is how we should approach this:

* `bodhi-server` produces:
    * `bodhi-server`
    * `bodhi-composer`
* `bodhi-client` produces
    *  `bodhi-client`
* `python-bodhi-messages` produces:
    * `python3-bodhi-messages`

since everything but bodhi-messages is an application rather than a library, right?

the packaging guidelines state the following (https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_application_naming)

```
Packages that primarily provide applications, services or any kind of executables SHOULD be named according to the general [Fedora naming guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Naming/) (e.g. ansible).

Consider adding a virtual provide according to [Library naming](https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_library_naming) above (e.g. python3-PROJECTNAME), if it would help users find the package.
```

no idea how to do a `virtual provide` tho

**Comment by mattiaverga** [comment]
> 
> no idea how to do a `virtual provide` tho

Just put a `%py_provides python3-bodhi-client` [here](https://github.com/fedora-infra/bodhi/blob/2cd1d4455efea6386361a239067fa9ba98f6d69d/bodhi-client/bodhi-client.spec#L20) and a `%py_provides python3-bodhi-server` [here](https://github.com/fedora-infra/bodhi/blob/2cd1d4455efea6386361a239067fa9ba98f6d69d/bodhi-server/bodhi-server.spec#L48). 
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#Automatic-unversioned-provides

The naming scheme you listed seems consistent with Fedora Packaging.

I think we should also add proper obsoletes in bodhi-client.spec:
```
Obsoletes: python-bodhi-client <= 5.7.4-1
Obsoletes: python3-bodhi-client <= 5.7.4-1
```

Finally, what about bodhi-docs? It would probably make sense to rewrite the docs so that each module has its documentation, builds it and provide it on their own. Bodhi-client, for example, should provide the man pages in the built RPM. And maybe we can now move the online docs to readthedocs, dropping static pages we currently serve through whitenoise (in the past I tried to build bodhi cos on RTD, but it wasn't possible because of dependencies).
