### ISSUE TITLE
Unexpected: "Related: rhbz#2059201, rhbz#2059188, rhbz#2057738" in the changelog closed the 3 bugzillas

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/bodhi#4404]
I've put this in the changelog:

 - Related: rhbz#2059201, rhbz#2059188, rhbz#2057738

And all three bugzillas were closed by the update. https://bodhi.fedoraproject.org/docs/user/automatic_updates.html#associate-bugs-to-automatic-updates explicitly says:

 - `fix(es)|close(s)|resolve(s)(:)` is needed
 - multiple bugzillas separated by comma won't work

**Comment by mattiaverga** [comment]
That's because there were multiple users requests to relax the regex used to catch bug ids and that has been done downstream in ansible:
https://pagure.io/fedora-infra/ansible/c/0de9fdade7625d3e046a79eb638f75809b8d2a95?branch=main

Since Bodhi defaults have not been changed I didn't update Bodhi docs... maybe I should add a specific paragraph for Fedora behavior to better describe this.
