### ISSUE TITLE
Vagrant unusable

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4445]
The switch to using authentication provided by Tinystage has made the vagrant development environment almost unusable:
- a user cannot login with their account (unless they manually add it to tinystage)
- tinystage misses some groups which Bodhi needs (for example, the `packager` group or those defined into the `admin_groups` and `admin_packager_groups` setting)
- trying to login causes a 400 - Bad Request - Invalid redirect_uri

Moreover, #4436 breaks some paths defined with the `%(here)s` directive.

**Comment by ryanlerch** [comment]
> The switch to using authentication provided by Tinystage has made the vagrant development environment almost unusable:
> 
> * a user cannot login with their account (unless they manually add it to tinystage)

Not sure if there is much we can do about this one, other than document that this is the case -- might be able to add something to the tinystage provisioning setup to allow a user to easily add themself? The main issue here is we cannot use stg.accounts.fp.o with oidc for testing setups because each client needs to be registered. Also, for privacy issues we cant expose a dump of the the accounts data to use in the tinystage IPA.

Since the admin password for the tinystage is not secure, (i.e. admin/password) and only used locally, we should be able to create this account from the bodhi vagrant provisioning step, right? We probably need some user input here though.

> * tinystage misses some groups which Bodhi needs (for example, the `packager` group or those defined into the `admin_groups` and `admin_packager_groups` setting)

Same with this one. WE can add these groups to tiny-stage when provisioning bodhi

> * trying to login causes a 400 - Bad Request - Invalid redirect_uri

I *think* this is because you are using http:// rather than https:// on the bodhi machine. we really should turn off http so this doesnt happen.

> 
> Moreover, #4436 breaks some paths defined with the `%(here)s` directive.

**Comment by mattiaverga** [comment]
Maybe it's best to provide some predefined users instead of having an interactive prompt during machine provisioning. If a developer wants to use their real account can always provision the machine with the `--use-staging` parameter (is that still working after the tinystage changes?).

I think we need at minimum the following groups defined in tinystage IPA:
`packager`, `provenpackager`
And we may provide three users for testing purposes:
`guest` with no packaging access
`packager` in the same group
`provenpackager` in both the `packager` and `provenpackager` group

Then we have to adjust the `validate_acl` method:
https://github.com/fedora-infra/bodhi/blob/85cc57943407969454c6cbadbabc645beef304a8/bodhi-server/bodhi/server/validators.py#L556-L562
