### ISSUE TITLE
please disable dependabot

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/bodhi#4507]
Can we have dependabot stop spamming with PRs? It now started to spam also my fork, so I now have a costant flood of usefulness emails coming from fedora-infra/bodhi and my fork of it.
Please either tweak the configuration file or disable it (no one is paying attention to its PRs as well)

**Comment by abompard** [comment]
> Can we have dependabot stop spamming with PRs? It now started to spam also my fork, so I now have a costant flood of usefulness emails coming from fedora-infra/bodhi and my fork of it.

Huh, it shouldn't be acting on your fork. We should definitely fix that.

> Please either tweak the configuration file or disable it

Well, we do need to keep our dependencies up-to-date somehow. I see two options:
- auto-merge the dependabot updates even on major version updates (they are currently auto-merged for minor and patch version updates). Downside: this would not limit the amount of email you get.
- switch to something else that can do gouped updates, something that dependabot [has on its roadmap](https://github.com/github/roadmap/issues/148) but does not have yet.
Any other idea?

> (no one is paying attention to its PRs as well)

I beg to differ :-) Minor and patch updates that pass tests are automatically merged, and I go look and approve the others for time to time. When they fail to build it's usually a sign that something's wrong with CI, as it's currently the case because of the new major release of greenwave, and then it's useful information because CI would fail with PRs for the same reason. I try to fix it in that case too. Although I do it when I don't have anything more urgent, which is not so frequent unfortunately. But others can too! (even though I agree it's not the most fun work)

**Comment by mattiaverga** [comment]
Yeah, sorry, I've opened this ticket when I saw tens of PRs failing due to missing permissions for the bot to approve and merge successful PRs. It now seems to work and I see that those not merging are due to really failing tests.

I still get PRs in my fork though, even if I disabled github actions in my fork's setting... not sure how to stop dependabot trying to push to my fork.
