### ISSUE TITLE
`bodhi updates edit UPDATE` disables autokarma and autotime

### ISSUE THREAD

**Issue by juhp** [fedora-infra/bodhi#4563]
I have been using `bodhi updates edit UPDATE` _with no options_ as workaround for unlocking submitted sidetag updates.
(Yes that is probably a hack but apart from some timing issues, it seems to work.)

However I noticed anyway that this command seems to disable autokarma and autotime?
which does not seem to desireable?

Admittedly running edit with no options is probably not that common (except for this workaround perhaps),
but I would not expect it to change the state of the update.

**Comment by juhp** [comment]
This seems kind of worse now I am afraid, with bodhi-client-6.0.0-2 I get:

`ERROR: This update was created from a side-tag. Please add --from_tag and try again.`

(That should be `--from-tag`.)  But if I try that I get:

`{"status": "error", "errors": [{"location": "body", "name": "from_tag", "description": "The supplied from_tag doesn't exist."}, {"location": "body", "name": "builds", "description": "ACL validation mechanism was unable to determine ACLs."}]}`

I guess I should not delete the sidetag until finalizing the update details. 
(Also doesn't bodhi already know that the update was from a sidetag?)

**Comment by mattiaverga** [comment]
Well, there has been no bodhi update since you opened this ticket, and #4564 has not yet been deployed.

However, I've screwed up things in #4482 and I'm going to add a fix in #4564 which will be available in the next release (or you can build bodhi-client yourself from the PR and try it out). Basically, I'm going to not requiring the `--from-tag` flag if the update being edited is from a side-tag. In these cases, the build list is always refreshed from the side-tag in the backend (that's how it used to work before my faulty PR). It would be nice in future to add a way to let the user choose to refresh the buildlist or not, but it's not so easy and I already caused too much problems...

**Comment by juhp** [comment]
> Well, there has been no bodhi update since you opened this ticket, and #4564 has not yet been deployed.

(I updated to bodhi-client-6.0.0-2.fc36 on Friday:)

**Comment by mattiaverga** [comment]
> > Well, there has been no bodhi update since you opened this ticket, and #4564 has not yet been deployed.
> 
> (I updated to bodhi-client-6.0.0-2.fc36 on Friday:)

It was only a rebuild, no code changes (same 6.0.0)

**Comment by juhp** [comment]
Alright I am not here to argue, but I don't see any earlier stable build of bodhi-client-6.0.0 for F36 in Bodhi... happy to be shown wrong though

**Comment by mattiaverga** [comment]
I think I misunderstood. Indeed, the problem reported was introduced with 6.0.0. The fix will be probably released with the next bugfix release (6.0.1?).
If you need a fix ASAP and you're willing to test the fix, you can manually download and install the RPMs built as part of the PR tests at https://github.com/fedora-infra/bodhi/actions/runs/2524168750 (look at the bottom of the page, you'll find F35, F36 and Rawhide RPMs).

**Comment by juhp** [comment]
Okay thanks - I have installed bodhi-client-6.0.0^202206191348git0fe1ded-1.fc36 - will try it out next time I have a chance to push a sidetag update.
