### ISSUE TITLE
CLI does not get user name from `~/.fedora.cert` any more

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/bodhi#474]
The `bodhi` CLI command used to figure out my username from `~/.fedora.cert` (I think) - it knew I was 'adamwill' not 'adamw', anyway. Since Bodhi 2.0 arrived, it doesn't work any more, it thinks I'm adamw unless I pass `-u adamwill`.

**Comment by ryanlerch** [comment]
@AdamWill is this one still an issue? the Bodhi CLI uses openid now, so i assume this one is no longer an issue.

Feel free to re-open if this is still an issue.

**Comment by AdamWill** [comment]
Nope, it's still a problem. Check it:

    [adamw@adam nightlies]$ bodhi updates edit --user adamwill fedfind-3.6.1-1.el6
    notes is missing
    [adamw@adam nightlies]$ bodhi updates edit fedfind-3.6.1-1.el6
    Password: 

I don't think I can re-open the issue, I think you have to.

**Comment by bowlofeggs** [comment]
@AdamWill I think it did know your username since it prompted you for your password but not your username. The Bodhi session expires regularly on some interval (can't remember for sure, maybe 2 weeks, maybe 30 days?), and when that happens it will prompt for your password. But if you have a bodhi session in ```~/.fedora/openidbaseclient-sessions.cache``` then it should be able to figure out your username now.

**Comment by AdamWill** [comment]
"I think it did know your username since it prompted you for your password but not your username."

No, it didn't, because I entered my password and it failed to authenticate properly. It likely guessed 'adamw', my system user name, but that's not the same name as my FAS account.

**Comment by AdamWill** [comment]
[adamw@adam createhdds (master)]$ bodhi updates edit fedfind-3.6.1-1.el6
    Password: (entered correct FAS password for adamwill)
    Authentication failed: Check your FAS username & password

**Comment by bowlofeggs** [comment]
@AdamWill another possibility is that it is using the ```USERNAME``` environment variable. I'm starting to think that using that environment variable is a Bad Idea™, because it seems to be set on many people's systems (it isn't on mine) to the same as ```USER```. Can you confirm if ```USERNAME``` is set for you, and if you think that might be the problem?

If you do think that's the problem, let's file a new issue about it. We should probably choose a better environment variable name, or just not use an environment variable at all. I added the environment variable as a workaround to the bodhi2 client's bad auth problems that were (mostly) recently solved. If you don't think ```USERNAME``` is to blame, let's reopen this to see if we can figure it out.

**Comment by ralphbean** [comment]
A point of data:  I have ``BODHI_USER=ralph`` set in my environment.  I don't know what docs (if any) instructed me to add it.

**Comment by AdamWill** [comment]
[adamw@adam tmp]$ echo $USERNAME
    adamw
    [adamw@adam tmp]$ echo $BODHI_USER
    
    [adamw@adam tmp]$

**Comment by AdamWill** [comment]
There's some code in GDM which looks like it's setting the `USERNAME` env var:

https://git.gnome.org/browse/gdm/tree/common/gdm-common.c#n575

I'm not sure of the context there, but it looks a lot like it could be the reason.

**Comment by bowlofeggs** [comment]
@AdamWill Ah! That explains this - @ralphbean was helping a Bodhi contributor this weekend who also had ```USERNAME``` set during flock - that was causing Bodhi's unit tests to fail. I use a different login manager, which explains why I don't have it.

I think we can consider this a new issue. Bodhi really shouldn't use a conflicting env variable with GDM since that's obviously a very popular login manager. I've filed an issue about this:

https://github.com/fedora-infra/bodhi/issues/1789
