### ISSUE TITLE
"How to install" doesn't provide correct working instructions

### ISSUE THREAD

**Issue by heis2201** [fedora-infra/bodhi#4843]
For reporting of the issue, let's use the following package update as example:
https://bodhi.fedoraproject.org/updates/FEDORA-2022-9c9698b680

The "How to install" box provides a `dnf --advisory=xxx` command which doesn't do what it says it would do, namely install the packages of that particular advisory.

**Comment by abitrolly** [comment]
And here is the log with the problem https://ask.fedoraproject.org/t/f37-testing-updates-dont-install/29291

**Comment by mattiaverga** [comment]
I think the main issue was that the first time you tried with
`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-9c9698b680`
the update was not yet available on mirrors. An hour later, it was.

The trailing `\*` is only needed with `dnf install`, because you need to tell dnf what package to install. With `upgrade` command, dnf should automatically find the packages in the update that need to be upgraded.

I just tried the command provided on several other upgrades and always work for me.

**Comment by abitrolly** [comment]
@mattiaverga if that's true, then mirror synchronization took almost 6 hours according to the log https://bodhi.fedoraproject.org/updates/FEDORA-2022-9c9698b680

Why mirror synchronization is not real-time?

**Comment by mattiaverga** [comment]
> @mattiaverga if that's true, then mirror synchronization took almost 6 hours according to the log https://bodhi.fedoraproject.org/updates/FEDORA-2022-9c9698b680
> 
> Why mirror synchronization is not real-time?

It depends on how different mirrors around the world are set to schedule their synchronization... in the worst case (I think) a mirror can synch 24h later and if your system is pointing at that mirror...
Bodhi only pushes to the main mirror. In the past I remember that one could configure yum/dnf to not use mirrors, but point a specific mirror or the main mirror.

**Comment by abitrolly** [comment]
I better paraphrase the question. Why mirrors do not synchronize themselves in real-time like blockchain networks do?

**Comment by heis2201** [comment]
Again, as said the in previous comment, the system is not designed to push to the mirrors. Each mirror is configured to pull the latest packages from the main download server by the volunteers and volunteer organization that runs the mirrors.
See https://github.com/fedora-infra/mirrormanager2/

Again, if you think you need zero delay, just set your .repo files to use the main download server. However, consider the additional load on the main server and imagine every user would point to the main server instead of the mirrors...

**Comment by abitrolly** [comment]
@heis2201 I understand how it works, but thanks for explaining it once more. I don't understand why there is no discussion about how effective is this way. Blockchain nodes can be run by anybody, and economic incentives in it guarantee that it is not only volunteers who run them. Information is synced in blocks, blocks are signed and passed between parties almost in real-time. OpenDHT allows to discover peers and sync with them. This prevents both load on the central server, and mirrors that are lagging critical updates by hours if not days.

**Comment by mattiaverga** [comment]
@abitrolly sorry, but this is not the right place for such discussion. It's not something that can be done Bodhi side.

**Comment by abitrolly** [comment]
@mattiaverga closing the issue without resolution is so-so. Like you don't want root server to be hammered, so you don't provide interface to see which mirror is used, which mirror is up to date, and you don't want to discuss what can be done to prevent it. You say "this is not the right place", but the problem is not resolved and you don't specify where is the right place. Yea, I know all we volunteers, and I am broke too, but still it feels mean.

**Comment by heis2201** [comment]
How about you start a productive discussion in one of the following places?

 - https://discussion.fedoraproject.org/c/project/7
 - https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/
 - https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/

**Comment by abitrolly** [comment]
Need to find a job and stop wasting my time. It is useless to discuss. If I have to propose, I have to implement it, and I don't have a luxury of doing this for free anymore.
