### ISSUE TITLE
Progress bar please

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/bodhi#497]
When a "submit" or "push", the only information about the work is the rotating artichoke.

Bad... bad...

Please add some "progress bar", or something more clear.

**Comment by cicku** [comment]
Is it really needed :question:

**Comment by remicollet** [comment]
Yes.

On another distro (you will guess what one) the errata tool include such a progress bar.
And it "seems" it is much more  fast ;)

**Comment by cicku** [comment]
And integrated with fedmsg?

**Comment by hguemar** [comment]
For instance, due to a javascript failure, you update never reach bodhi backend, you cannot receive then a notification of failure, as fedmsg can't receive that notification.
And if you're working on something else, you may forget about it without feedback.

There's not a single workflow that fits them all, if Remi thinks he could improve his productivity (and probably many other folks), it's up to maintainers to decide to implement it or not.

**Comment by ralphbean** [comment]
We currently:

- Spin the cabbage.
- Change your mouse cursor to the 'wait' icon (a spinning wheel, or something else depending on your browser).

We could also add a little progress bar at the top with pace.js or something like it.  I'm not opposed.

**Comment by ralphbean** [comment]
Hey, I spent **way** too much time trying to get this to work.  It's not worth it.  We already have other progress indicators in place, no need for a third.

If someone **really* wants to work on this, please do!

**Comment by remicollet** [comment]
> We already have other progress indicators in place,

Sorry ? which ones ? The rotating artichoke ?

**Comment by cicku** [comment]
:joy:

**Comment by ralphbean** [comment]
> Sorry ? which ones ? The rotating artichoke ?

Yes.  And the changed mouse cursor.
