### ISSUE TITLE
Possible tagging issues with https://bodhi.fedoraproject.org/updates/FEDORA-2015-14271

### ISSUE THREAD

**Issue by nirik** [fedora-infra/bodhi#504]
There's a report on the devel list that 

https://bodhi.fedoraproject.org/updates/FEDORA-2015-14271

has had some packages tagged stable, but others not. 

Fix tags on the packages in the update, figure out why they might have been mistagged and fix that underlying issue.

**Comment by nirik** [comment]
I see in logs: 

ejected from the push because u"Cannot find relevant tag for kf5-frameworkintegration-5.13.0-2.fc23: ['f23-updates-candidate', 'f23-updates-testing-pending', 'f23-updates-pending', 'f23-kde']"

So perhaps something with that package caused the rest of the update to not be tagged correctly?

**Comment by kkofler** [comment]
You need to validate the tags before you start tagging packages, failing with parts of the update group already tagged is a very bad idea.

**Comment by kkofler** [comment]
As I wrote on the mailing list:

> I'm not sure how you reached that conclusion, but ok...

`koji latest-pkg f23` _(the packages in the update)_
Some packages from FEDORA-2015-14271 are in the f23 tag, some are not.

**Comment by kkofler** [comment]
See also https://fedorahosted.org/rel-eng/ticket/6246

**Comment by AdamWill** [comment]
nirik: the same 'ejected from the push' message is present in the update (twice), but in both cases it looks like *all* the packages are listed. At least both `kf5-kconfigwidgets` (which *did* get tagged stable) and `kf5-filesystem` (which did *not* get tagged stable) are listed in the 'ejected from push' message both times.

**Comment by kkofler** [comment]
I think the root cause of the mess is that `kf5-frameworkintegration-5.13.0-2.fc23` was built in a side tag and we apparently forgot to tag it with the proper updates-candidate tag before adding it to the update. However, Bodhi needs to do the error checking much sooner. In Bodhi 1, when we made that mistake, the package was rejected right when we attempted to add it to an update. Bodhi 2 only noticed it in the middle of the tagging process of the push, which is the worst possible moment to notice. The validation needs to happen before the first packages get tagged, ideally already at submission/editing time as Bodhi 1 did (but for robustness, it's a good idea to recheck at the beginning of the push process, before you start moving tags).

**Comment by lmacken** [comment]
It looks like that build was tagged properly as a candidate before getting submitted to bodhi. 
```
Wed Aug 26 05:15:13 2015: kf5-frameworkintegration-5.13.0-2.fc23 tagged into f23-kde by dvratil [still active]
Wed Aug 26 05:34:22 2015: kf5-frameworkintegration-5.13.0-2.fc23 tagged into f23-updates-candidate by dvratil [still active]
Wed Aug 26 06:30:49 2015: kf5-frameworkintegration-5.13.0-2.fc23 tagged into f23-updates-testing-pending by bodhi [still active]
Thu Sep  3 08:31:35 2015: kf5-frameworkintegration-5.13.0-2.fc23 tagged into f23-updates-pending by bodhi

```

It it never actually made it into updates-testing. The issue is that bodhi never re-requested that the update get pushed back to testing after a new build was added. This bug has since been resolved.

So, tagging this build into testing by hand and re-requesting stable should hopefully solve the immediate problem.

**Comment by lmacken** [comment]
So I think the core of this issue is #521

**Comment by nirik** [comment]
In the mean time, we manually have fixed up tags for this update and are going to repush it to stable to get it all in sync.
