### ISSUE TITLE
Don't show "page only works with JavaScript enabled" warning when JS is enabled

### ISSUE THREAD

**Issue by mcatanzaro** [fedora-infra/bodhi#627]
When loading various pages, including the New Update page, Bodhi flashes a warning that "this page only works with JavaScript enabled." Then the warning disappears after a fraction of a second, because I do in fact have JavaScript enabled.

**Comment by ralphbean** [comment]
Yeah, the way it works is:

- We start showing the page with that warning and then
- if JS is enabled, then it removes that warning and shows the real content.

That should be fine, but we haven't optimized our page load to get that warning-removal JS running fast enough.  If anyone happens to have good concrete ideas about how to do that, we'd appreciate if you shared them.  Otherwise, we have to do some research.

**Comment by jasontibbitts** [comment]
The element hiding happens at the bottom of update_form.js.  Even though that's the first script loaded, it might be worth trying to just move $("#js-warning").addClass('hidden'); up to the second line of the script so it runs before any other initialization.
