### ISSUE TITLE
should push to stable immediately if will be automatically set to request stable at time of push to testing

### ISSUE THREAD

**Issue by plajimmoi** [fedora-infra/bodhi#632]
Example:
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16569

This update was pushed to testing at 2015-09-27 00:42:54
It was then automatically requested for stable based upon karma 42 seconds later.
Then the package had to wait 15 hours to be pushed to stable, even though it already met the karma requirements for automatic request for stable before the push to testing.

Instead of (or in addition to?) pushing it to testing, it should have been automatically pushed to stable at the time it pushed to testing, rather than having to wait until the next time updates get pushed, which in this case was 15 hours later (in some cases the wait seems to be longer still).

Probably the best way to approach this is for Bodhi to automatically change the request from testing to stable if the Karma requirements for automatic request for stable have been reached before the package makes it to testing.

Timeliness of updates is important for security, for example. In this case, the sqlite package was holding up for several days a security update for firefox which depended upon it (https://bodhi.fedoraproject.org/updates/FEDORA-2015-16455). (Actually, it looks like this firefox package is another example where the push to stable was delayed for the same reason.)

**Comment by dustymabe** [comment]
This is a much desired feature of mine as well. I talked with @nirik about this tonight and we do not believe it violates any of the [written policy](https://fedoraproject.org/wiki/Updates_Policy#All_other_updates) to have an update go straight from `pending` `->` `stable`  if the karma threshold has been reached.

Often times if people have gone out of their way to grab the package and test it before it hits updates-testing it is because the update is desired to be made available faster and thus having this >= 24hour wait can be counter-productive.

**Comment by trishnaguha** [comment]
+1 to the feature. It definitely makes sense to push the updates directly to stable when it has enough karma before hitting the testing repo. I am working on it.
