### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#637]
:snake: :three:

**Comment by ralphbean** [comment]
The ``BodhiClient`` in python-fedora should be [python3 ready now](https://github.com/fedora-infra/python-fedora/pull/156) as of [python-fedora-0.6.0](https://bodhi.fedoraproject.org/updates/FEDORA-2015-6093e9acc7).

**Comment by bowlofeggs** [comment]
There are a few blockers to migrating all of Bodhi to Python 3:

http://fedora.portingdb.xyz/pkg/bodhi/

It may be possible to get the client to work with Python 3, but there is some uncertainty in my mind about it without trying it. The client and server are part of the same codebase currently, and share a single setup.py. It might be possible to do something sneaky like run `python3 setup.py install` and then remove the server bits from the install, leaving only the client. This would be weird to do but if it works it might be an option.

The cleanest approaches would be to port the server to Python 3, or to separate the client into a different Python package.

**Comment by bowlofeggs** [comment]
A issue was filed in BZ about this: https://bugzilla.redhat.com/show_bug.cgi?id=1024795

**Comment by bowlofeggs** [comment]
This is in progress by @frenzymadness: #2115

**Comment by abitrolly** [comment]
So how it goes?

**Comment by frenzymadness** [comment]
I believe that almost all Bodhi code is Python 3 ready and we are working on tests now. There are still more than 300 tests skipped in Python 3 but it's mostly caused by tests incompatibility and not tested code incompatibility. Moreover, I fixed some bugs in the latest pull requests which may fix a lot more than included in PR so I'll test it soon.

**Comment by bowlofeggs** [comment]
Update: We are very close to done with this. There are just a few lines that are missing test coverage under Python 3 now!

**Comment by abitrolly** [comment]
http://fedora.portingdb.xyz/pkg/bodhi/ shows that `packagedb-cli` dependency is not ported.

**Comment by frenzymadness** [comment]
> http://fedora.portingdb.xyz/pkg/bodhi/ shows that `packagedb-cli` dependency is not ported.

You're right but this isn't a problem because packagedb itself is deprecated and therefore the support for it can be dropped when Bodhi will be ready for switch to Python 3.

**Comment by abitrolly** [comment]
@frenzymadness why it is not possible to drop the support right now?

**Comment by abitrolly** [comment]
Nevermind, I found this https://github.com/fedora-infra/bodhi/issues/1970

**Comment by bowlofeggs** [comment]
Update on this: I am currently building a 3.11.0 beta that I intend to deploy to staging on Python 3 only. I hit a few small snags along the way, but have opened pull requests to fix them all.

As for pkgdb, I still plan to drop that in Bodhi 4.0.0, which will likely happen "soon", but is not a blocker for Bodhi being deployed on Python 3 since @frenzymadness made sure the code doesn't blow up on Python 3 (it won't work with pkgdb on Python 3, but will work with Pagure just fine).

**Comment by bowlofeggs** [comment]
Bodhi was deployed on Python 3 a couple weeks ago. There were a few issues discovered after deployment, but Bodhi seems to be stable on Python 3 now. Thanks to @frenzymadness for all the help!

**Comment by frenzymadness** [comment]
That's a great achievement and a very nice Christmas gift! Thank you!

**Comment by abitrolly** [comment]
I am still curious what the issues are?

**Comment by bowlofeggs** [comment]
@abitrolly The post-release issues that were discovered are documented in the release notes for 3.11.1 and 3.11.2: https://bodhi.fedoraproject.org/docs/user/release_notes.html
