### ISSUE TITLE
Don't show EOL releases in user's view

### ISSUE THREAD

**Issue by kalev** [fedora-infra/bodhi#752]
https://bodhi.fedoraproject.org/updates/?user=kalev&status=testing still shows a F21 gom-0.3.1-1.fc21 update, even though F21 is long EOL. I think it would be better to hide all EOL updates as there's nothing the user can do with these any more.

**Comment by ralphbean** [comment]
Hm.  It's a bit tricky, because that same endpoint is used to query for updates using *any* criteria (both UI and API).. and there's already a mechanism to control which releases get returned.  Take [this query](https://bodhi.fedoraproject.org/updates/?user=kalev&status=testing&release=f23) for example, which shows only your F23 testing updates.

One option would be to default the ``release`` argument to the list of active releases.  But then, how would you query for all updates, including old EOL updates (if you wanted them for some kind of report-generating script)?  Would you have to explicitly list all releases in the query?

**Comment by ralphbean** [comment]
Another idea:  I'm assuming you got to that page by clicking the ``Testing >`` link from [your profile page](https://bodhi.fedoraproject.org/users/kalev).  We could make *that link* include an explicit list of only the active branches... that way users could look at the URL and see explicitly what they're requesting.. and then modify it if they wanted to base a script off of the page.

**Comment by kalev** [comment]
Yup, that's exactly where I got the link. Sounds like a good solution to me, thanks.

**Comment by Fale** [comment]
Hi,
I'm experiencing the same problem.
See:
- https://bodhi.fedoraproject.org/updates/?user=fale&status=testing
- https://bodhi.fedoraproject.org/updates/FEDORA-2016-42c5c95430
- https://fedorahosted.org/rel-eng/ticket/6474

**Comment by deekej** [comment]
Same issue here:
https://bodhi.fedoraproject.org/updates/FEDORA-2016-6ecaf251f6

Would it be possible to actually delete the updates which are stuck in *testing* for EOL releases manually? I don't expect those updates to ever make it further, and if people need some data gathered they can do it before manually deleting it.

I'm not sure if this is not against some Bodhi policy at the moment, but we have the ability to *unpush* an update for current releases. IMHO we should have some similar (*delete*) option for an update in the EOL releases... :)

**Comment by mcepl** [comment]
me too … https://bodhi.fedoraproject.org/updates/FEDORA-2016-eb0392d623

**Comment by ryanlerch** [comment]
@bowlofeggs commented an idea for a solution to this here https://github.com/fedora-infra/bodhi/pull/1712#pullrequestreview-52980943

**Comment by bowlofeggs** [comment]
Related: https://github.com/fedora-infra/bodhi/issues/1736

**Comment by bowlofeggs** [comment]
I think we should do something to the objects to remove them from "testing" when a release gets archived, since updates are no longer truly being tested for F21. IMO, that should be the true fix for the issue.

There is a CLI tool called ```bodhi-manage-releases``` that releng uses when they want to archive a release. That tool makes API calls to Bodhi. I think we should have that API kill all non-stable updates when a release is archived, perhaps by revoking them.

As for the existing objects, I think we can write a database migration to do the same. Fixing the API will fix the issue for the future, and the migration will get the existing data to be consistent.

I think this approach will ensure that the user's profile page shows the right data while also making all other queries show the right data.

**Comment by puiterwijk** [comment]
@bowlofeggs The problem with just deleting them is that that means the data will be "false": It'll say that that update never existed, while it is in the testing repos.
Even post-EOL we should have consistent data on all packages in any repositories.

**Comment by bowlofeggs** [comment]
@puiterwijk Good point.

**Comment by thmo** [comment]
Any updates here?

**Comment by deekej** [comment]
Thanks! :)

**Comment by mcepl** [comment]
I would like to thank to, but I am still seeing ``youtube-dl-2016.12.09-1.fc23`` in my https://bodhi.fedoraproject.org/updates/?user=mcepl&status=testing . What is the ETA for the change?

**Comment by pypingou** [comment]
@mcepl it has been merged but not released yet. It'll be part of the next release.
