### ISSUE TITLE
[RFE] manual stable push based on karma

### ISSUE THREAD

**Issue by carlwgeorge** [fedora-infra/bodhi#796]
Bodhi has two scenarios for pushing updates to stable.

* manual stable push based on time
    1. auto-karma disabled
    2. 14 days in testing
    3. maintainer submits to stable via "push to stable" button
* automatic stable push based on karma
    1. auto-karma enabled
    2. karma threshold reached
    3. automatically submitted to stable

There is another scenario that seems to be allowed by policy, but not currently possible in bodhi.

* manual stable push based on karma
    1. auto-karma disabled
    2. karma threshold reached
    3. maintainer submits to stable via "push to stable" button

What would it take to have this feature added?

**Comment by trishnaguha** [comment]
@lmacken @ralphbean I want to work on it. I need some hints. How do I start? :)

**Comment by lmacken** [comment]
I haven't looked too deeply into what this change will require, but here is some info off the top of my head.

* Right now the "autokarma" checkbox enables the stable/unstable karma thresholds. The thresholds are currently ignored unless "autokarma" is enabled.

This proposes being able to keep "autokarma" disabled, but set thresholds that, when met, will allow the package to be manually pushed to stable.

I know the main update template logic will need to be modified. It's a bit hairy right now, so it might require some refactoring...
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/templates/update.html#L515-L543

You'll also want to grep around for 'autokarma' to see if any of that logic needs modification, like:
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/models/models.py#L709
https://github.com/fedora-infra/bodhi/blob/develop/bodhi/models/models.py#L865

**Comment by trishnaguha** [comment]
@lmacken Thanks for the hints :)
So is there any way to see or test the changes I'll be making? It would be really helpful if I can know that.

**Comment by lmacken** [comment]
Yeah, it shouldn't be too difficult to write a unit test for. It should basically:

 * Create an update with `autokarma=False` and `stable_karma` set to 1
 * Give the update 1 karma (as a differrent user). Example: https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/functional/test_updates.py#L2363-L2381
 * Ensure the `request` didn't get automatically set due to autokarma, since it should be disabled.
 * Get the html of the page, and ensure the text 'Push to Stable' is in there. Example of getting the html: https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/functional/test_updates.py#L422-L428

**Comment by trishnaguha** [comment]
@lmacken I just wrote the test for the feature. Could you please make sure is this what we want?
Here is the diff http://fpaste.org/342865/
The test is failing for `stable_karma` only. It is expecting `stable_karma` to be `None` .
So I just realized that the test is exercising through 
- autokarma disabled
- 14 days in testing
- maintainer submits to stable via "push to stable" button

Therefore I need to change the model as well. Correct me if I am wrong :).
Thanks!

**Comment by lmacken** [comment]
#772 seems to be related

**Comment by kkofler** [comment]
Yes, #772 is basically the same thing. The only difference is that I'm suggesting the check should be hardcoded at the minimum permissible `stable_karma` (i.e. usually 1), because I don't see the value of being allowed to disallow myself from pushing updates that the policy allows me to push, all the more because it'd just be a matter of changing the setting to be able to push it anyway. The configurable threshold makes sense for autokarma (to the extent that autokarma makes sense to begin with ;-) ), but not really for manual pushes where it is just an extra hoop to jump through for no gained value.

**Comment by bowlofeggs** [comment]
I believe that @trishnaguha fixed this in #821.
