### ISSUE TITLE
CLI --my-overrides is broken and then gives 404

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/bodhi#810]
When running "bodhi --my-overrides", this first error is that it passes req_params, which is invalid (should probably be params), and after fixing that it results in a 404.

**Comment by jwakely** [comment]
c.f. https://bugzilla.redhat.com/show_bug.cgi?id=1259681

**Comment by bowlofeggs** [comment]
Thanks for the bug report! It sounds like this is for bodhi-0.9 (I'm guessing since /usr/bin/bodhi is autogenerated in bodhi 2). I don't mind at all that you filed this here (in fact I appreciate bug reports no matter how they arrive!), but I prefer to use GitHub to track issues in Bodhi 2's codebase and Bugzilla to track issues with packaging and/or bodhi-0.9's codebase. It turns out there's already a BZ there about this:

https://bugzilla.redhat.com/show_bug.cgi?id=1259681

I will close this issue so we can track the issue in BZ. As I mentioned in one of the comments there, it is difficult for me to find the time to fix many bodhi-0.9 bugs (though I have fixed one so far!) so I can't promise I'll be able to fix this one before F25 goes EOL ☹
