### ISSUE TITLE
Updates list all testcases, not just those from a proper category

### ISSUE THREAD

**Issue by kparal** [fedora-infra/bodhi#824]
[This anaconda update](https://bodhi.fedoraproject.org/updates/FEDORA-2016-cd26edfec7) lists this test case:
[User:Pschindl/Draft/Testcase Anaconda custom partitioning](https://fedoraproject.org/wiki/User:Pschindl/Draft/Testcase_Anaconda_custom_partitioning?redirect=no)

We tried to get rid of that by renaming that page, but the original page remained as a redirect, and is still listed on the bodhi page. But I found out that it's not the core issue.

The core issue is that our [package test plan SOP](https://fedoraproject.org/wiki/QA:SOP_package_test_plan_creation) says that only testcases listed in `Category:Package_(packagename)_test_cases` should be displayed. So for anaconda, only these test cases should be visible:
https://fedoraproject.org/wiki/Category:Package_anaconda_test_cases

It seems that Bodhi does not search the available testcases according to the categories, but just by matching titles of all available test cases on the whole wiki (isn't that slow?). That's not correct. Please only show testcases from the correct category, according to the SOP, thanks.

CCing @AdamWill to make sure I understood the intended workflow and the SOP correctly :-)

**Comment by AdamWill** [comment]
note I edited the page quite recently and entirely removed its category memberships:

https://fedoraproject.org/w/index.php?title=User:Pschindl/Draft/Testcase_Custom_partitioning&diff=441497&oldid=420722

I think what actually was happening is that Bodhi wasn't respecting wiki comment blocks. I filed https://github.com/fedora-infra/bodhi/issues/822 for that.

but yeah, whatever the problem is, the intent is that Bodhi should only list pages that are members of the special category. Which means it shouldn't work off page names or ignore comment tags.

**Comment by bowlofeggs** [comment]
Is this still a problem?

**Comment by AdamWill** [comment]
Well, yeah. Click on the update in the original comment, and it still has the draft testcase at the bottom. The [most recent anaconda update in Bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2018-2789f6b6e7) (from two months ago) still has this problem.

An alternative theory here is that Bodhi doesn't ever check for pages *leaving* the relevant categories. That is, if it once notices that Some Page is in the `package_foo_test_cases` category, it will store that info somewhere and *never refresh it* - it never goes out to see if Some Page is *still* in that category. Is that possible?
