### ISSUE TITLE
weak and/or rich deps are not in repodata

### ISSUE THREAD

**Issue by igor-raits** [fedora-infra/bodhi#875]
```
[ignatenk@ignatenko tpm]$ sudo dnf --disablerepo=\* --enablerepo=fedora repoquery --supplements glibc-langpack-cs
Last metadata expiration check: 1 day, 3:42:23 ago on Tue Jul 26 08:59:25 2016.
(glibc = 2.23.1-7.fc24 and (langpacks-cs or langpacks-cs_CZ))
[ignatenk@ignatenko tpm]$ sudo dnf --disablerepo=\* --enablerepo=updates repoquery --supplements glibc-langpack-cs
Last metadata expiration check: 0:52:47 ago on Wed Jul 27 11:49:13 2016.
```

**Comment by igor-raits** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1319073

**Comment by pnemade** [comment]
Well the only reason I did not report this issue before because what can one do if you have been told that updates are composed on epel7 machines and epel7 do not have weakdeps support in RPM.

The information I got on 12th May from Dennis is this

`May 12 19:50:52 <dgilmore>      paragan: updates repos uses createrepo under the hood and f24 composes use createrepo_c`

**Comment by pnemade** [comment]
@lmacken Can you please check this issue and provide your comment here? I want to know when will bodhi start generating Weak dependency tags in repo metadata files?

**Comment by lmacken** [comment]
So I think this is just a matter of using `createrepo_c` instead of `createrepo`. Bodhi currently uses `mash` to generate the updates repositories, which uses the old `createrepo`. We've been planning to remove mash from the process by using Koji to generate the repos, using the new KojiSignedRepos Feature that has been in the works for a while.  https://pagure.io/koji/pull-request/54

Once that feature is merged, it shouldn't be very difficult to port the repo creation logic over to koji.

**Comment by nirik** [comment]
ok, we now are pushing updates on a fedora-24 instance and using rpm that understands weak deps. 
We didn't have to change from createrepo, just a newer rpm.
