### ISSUE TITLE
Stable push failed 

### ISSUE THREAD

**Issue by gbcox** [fedora-infra/bodhi#889]
Can you please advise?  This is the first time I've ever experienced this error - since testing went fine, I'm thinking something is wrong on the bodhi side.

dist.upgradepath FAILED for sphinx-2.2.11-2.fc24
        https://taskotron.fedoraproject.org/artifacts/all/31b42514-666a-11e6-a44e-525400120b80/task_output/sphinx-2.2.11-2.fc24.log

dist.upgradepath FAILED for sphinx-2.2.11-2.fc23
        https://taskotron.fedoraproject.org/artifacts/all/3233e18c-666a-11e6-a44e-525400120b80/task_output/sphinx-2.2.11-2.fc23.log

**Comment by bowlofeggs** [comment]
Hello @gbcox!

I believe these tests are actually from taskotron and not Bodhi (even though Bodhi is showing them to you), but maybe we can try to understand it together.

Looking at the first link, it sounds to me like it's upset that Fedora 25 has an older version (2.2.10) than the proposed update for Fedora 24 (2.2.11). Therefore, if the F24 update were pushed out, F25 users would have an older package version than F24 users. I may be interpreting it wrong, but that's my guess. What do you think?

**Comment by gbcox** [comment]
That could be, I built the package for F25 but didn't submit it to testing for F25 because I was under the impression it would be placed there automatically, since we're not even in alpha yet.  Are you saying you believe I need to submit this also to F25 for testing?

**Comment by bowlofeggs** [comment]
@gbcox Though the alpha hasn't happened, the bodhi activation point did occur (I think about two weeks ago?) which means that updates for Fedora 25 do need to go into Bodhi.

I bet that submitting the same update to Fedora 25 will solve the problem for you. Fingers crossed!

**Comment by gbcox** [comment]
Thanks, well I pushed it - and unfortunately it appears I need to wait another 7 days to get a fix which is need pushed.  It doesn't seem correct that this dependency would exist.  There may be reasons to patch a lower Fedora release rather that the current... and this would imply that you need to create a fake patch to trick the system into allowing you to patch the previous release.  That doesn't seem right. 
I'm thinking I need to escalate this unless I'm missing something here... seems like a flaw in the logic to me.  Do you know the group?  I looked on bugzilla, and there is a libtaskotron... is that it?

**Comment by bowlofeggs** [comment]
I think the rule does make sense. Consider this scenario:

1) A user has package-1.1.1 on Fedora 24.
2) Fedora 25 has package-1.0.1.
3) The user upgrades to Fedora 25, which will keep them on package-1.1.1 instead of 1.0.1.

There are two potential problems with this. For one, package-1.1.1 was not tested with the rest of Fedora 25's packages, so it may have unknown problems. Secondly, consider the scenario where upstream releases 1.1.2 and 1.0.2 as critical security fixes. If Fedora 25 is patched for 1.0.2, this theoretical user will stay on 1.1.1 which is vulnerable during a dnf upgrade.

The documentation for the test that you are reporting is here: https://fedoraproject.org/wiki/Taskotron/Tasks/upgradepath

If you would like to discuss this with Fedora QA, you can chat with them in #fedora-qa on Freenode. I'm going to close this issue since it's not a Bodhi issue. I hope that helps!

**Comment by gbcox** [comment]
Great... thanks for the information and your help.  The packages got pushed to stable after I submitted the update to F25.
